---
title: "Creates EMA features locally"
author: "John Curtin"
date: "`r lubridate::today()`"
output: 
  html_document:
  toc: true 
toc_depth: 4
knit: (function(input, ...) {
  rmarkdown::render(
    input,
    output_dir = dplyr::if_else(Sys.info()[["sysname"]] == "Windows",
                                "P:/studydata/risk/knits/gps", 
                                "/Volumes/private/studydata/risk/knits/ema")
  )
})
---
  
### Code Status
  
This code is replaced by code to create features on CHTC.  Will delete soon

### Notes  

### Setup
Constants: EDIT
```{r}
window <- "1day"  # window for calculating labels
period_durations <- c(12, 24, 48, 72, 168) # feature duration window
lead <-  0 # feature lead time
```


Absolute paths
```{r, paths}
switch (Sys.info()[['sysname']],
        # PC paths
        Windows = {
          path_raw <- "P:/studydata/risk/data_raw/qualtrics"
          path_shared <- "P:/studydata/risk/data_processed/shared"
          path_ema <- "P:/studydata/risk/data_processed/ema"},

        # IOS paths
        Darwin = {
          path_raw <- "/Volumes/private/studydata/risk/data_raw/qualtrics"
          path_shared <- "/Volumes/private/studydata/risk/data_processed/shared"
          path_lab_support <- "/Volumes/private/studydata/risk/data_processed/ema"}
        )
```


Libraries and Source
```{r}
library(here)
library(conflicted) # detect and warn about function conflicts
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")

library(tidyverse)
library(lubridate)
library(vroom)
library(furrr)
library(tictoc)

source(here("shared", "fun_features.R"))
```


### read in data
```{r}
dates <- vroom(here(path_ema, "study_dates.csv"), show_col_types = FALSE) %>% 
  mutate(study_start = with_tz(study_start, tz = "America/Chicago"),
         data_start = with_tz(data_start, tz = "America/Chicago"),
         study_end = with_tz(study_end, tz = "America/Chicago"),
         ema_end = with_tz(ema_end, tz = "America/Chicago")) %>% 
  glimpse()

labels <- vroom(here(path_ema, str_c("labels_", window, ".csv")), show_col_types = FALSE) %>%
  mutate(dttm_label = with_tz(dttm_label, tz = "America/Chicago")) %>% 
  arrange(subid, dttm_label) %>% 
  glimpse()

ema <- vroom(here(path_shared, "ema_morning.csv"), show_col_types = FALSE) %>% 
  bind_rows(vroom(here(path_shared, "ema_later.csv"), 
                  show_col_types = FALSE)) %>% 
  mutate(start_date = with_tz(start_date, tz = "America/Chicago"),
         subid = as.numeric(subid)) %>% 
  rename(dttm_obs = start_date) %>% 
  select(-response_id, -end_date, -finished, -status, -utc, -send_date, -send_time,
         -ema_1_1, -ema_1_2, -ema_1_3, -ema_1_4, -ema_1_5, -ema_1_6, -ema_type) %>% 
  relocate(subid) %>% 
  mutate(ema_1 = if_else(ema_1 == "No", 1, 2), # cant use 0
         ema_2 = ema_2 + 1,
         ema_3 = ema_3 + 1,
         ema_4 = ema_4 + 1,
         ema_5 = ema_5 +1) %>%   
  arrange(subid, dttm_obs) %>% 
  glimpse

# pivot longer to allow feature function to loop over ema items across rows
ema_long <- ema %>% 
  pivot_longer(
    cols = starts_with("ema_"),
    names_to = "ema_num",
    values_to = "response"
  ) %>% 
  glimpse
```


### feature function

```{r}

get_features_subid <- function(the_subid, labels, ema_long, dates, period_durations, 
                         lead, col_name, data_type_col_name, data_type_values) {
  
  labels <- labels %>% filter(subid == the_subid)
  
  features <- foreach(i_label = 1:nrow(labels), .combine="rbind") %do% {
  
    label <-  slice(labels, i_label)
    subid <- label$subid 
    dttm_label <-  label$dttm_label
    
    # median
    feature_row <- score_median(the_subid = subid, 
                              the_dttm_label = dttm_label,
                              x_all  = ema_long,
                              period_durations = period_durations,
                              lead = lead, 
                              data_start = dates, 
                              col_name = "response", 
                              data_type_col_name = "ema_num", 
                              data_type_values = str_c("ema_", 1:10))
  
    # max
    feature_row <- feature_row %>% 
      full_join(score_max(the_subid = subid, 
                              the_dttm_label = dttm_label,
                              x_all  = ema_long,
                              period_durations = period_durations,
                              lead = lead, 
                              data_start = dates, 
                              col_name = "response", 
                              data_type_col_name = "ema_num", 
                              data_type_values = str_c("ema_", 1:10)), 
                 by = c("subid", "dttm_label"))
    
    # min
    feature_row <- feature_row %>% 
      full_join(score_min(the_subid = subid, 
                              the_dttm_label = dttm_label,
                              x_all  = ema_long,
                              period_durations = period_durations,
                              lead = lead, 
                              data_start = dates, 
                              col_name = "response", 
                              data_type_col_name = "ema_num", 
                              data_type_values = str_c("ema_", 1:10)), 
                 by = c("subid", "dttm_label"))
    
    feature_row
  }
}
```

### Get features
Set up parallel backend
```{r}
# use furrr to future map over subids (the_subid) when making labels
(n_cores <- parallel::detectCores(logical = FALSE))
plan(multisession, workers = n_cores)

```

```{r}
tic()
subids <- unique(labels$subid)
features <- subids %>% 
  future_map_dfr(~get_features_subid(.x, labels, ema_long, dates, period_durations, lead, 
                        col_name = "response", 
                        data_type_col_name = "ema_num", 
                        data_type_values = str_c("ema_", 1:10)))
toc()
plan(sequential)
```

### Finish up
```{r}
features <- features %>% 
  mutate(lapse = labels$lapse) %>% 
  relocate(subid, dttm_label, lapse) %>% 
  vroom_write(path_ema, str_c("features_", window, ".csv"), delim = ",") %>% 
  vroom_write(path_ema, str_c("features_", window, ".csv.xz"), delim = ",") %>% 
  glimpse()
```
