---
title: "Make combined EMA"
author: "John Curtin"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = dplyr::if_else(Sys.info()[["sysname"]] == "Windows",
      "P:/studydata/risk/knits/ema", 
      "~/mnt/private/studydata/risk/knits/ema")
    )
  })
editor_options: 
  chunk_output_type: console
---

### Code Status

Complete

### Notes

Combines the morning and later ema files from shared folder and saves in processed data
for ema


Absolute paths
```{r, absolute paths}
switch (Sys.info()[['sysname']],
        # PC paths
        Windows = {
          path_shared <- "P:/studydata/risk/data_processed/shared"
          path_ema <- "P:/studydata/risk/data_processed/ema"},

        # IOS paths
        Darwin = {
          path_shared <- "/Volumes/private/studydata/risk/data_processed/shared"
          path_ema <- "/Volumes/private/studydata/risk/data_processed/ema"},
        
        # IOS paths
        Linux = {
          path_shared <- "~/mnt/private/studydata/risk/data_processed/shared"
          path_ema <- "~/mnt/private/studydata/risk/data_processed/ema"}
        )
```

Packages for lab workflow 
```{r, packages_workflow, message=FALSE, warning=FALSE}
library(conflicted) 
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
```


Packages for script
```{r, packages_script, message=FALSE, warning=FALSE}
library(tidyverse)
```


### Process and save ema
```{r}
ema_morning <- read_csv(file.path(path_shared, "ema_morning.csv"), show_col_types = FALSE) %>% 
  glimpse()

ema_later <- read_csv(file.path(path_shared, "ema_later.csv"), show_col_types = FALSE) %>% 
  glimpse()
```

```{r}
ema <- ema_morning %>% 
  bind_rows(ema_later) %>% 
  mutate(subid = as.numeric(subid)) %>% 
  select(-response_id, -start_date, -finished, -status, -utc, -send_date, -send_time) %>% 
  #NOTE: THIS IS A CHANGE TO MAKE SURE THE EMA IS TIMESTAMPED WHEN IT IS COMPLETED.
  #PREVIOUSLY USED start_date
  rename(dttm_obs = end_date) %>% 
  glimpse()
```


```{r}
ema %>% 
  write_csv(file.path(path_ema, "ema.csv"))
```
