---
title: "Clean and process location data from interviews"
author: "John Curtin & Hannah Moshontz"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = dplyr::if_else(Sys.info()[["sysname"]] == "Windows",
      "P:/studydata/risk/knits/gps", 
      "/Volumes/private/studydata/risk/knits/gps")
    )
  })
---
### Code status


This is not yet usable code!  See also cln_interviews


### Notes


### Set up Environment

Absolute paths
```{r, paths}

switch (Sys.info()[['sysname']],
        # PC paths
        Windows = {
          path_raw <- "P:/studydata/risk/data_raw"
          path_shared <- "P:/studydata/risk/data_processed/shared"
          path_lab_support <- "P:/toolboxes/lab_support"},

        # IOS paths
        Darwin = {
          path_raw <- "/Volumes/private/studydata/risk/data_processed/gps"
          path_shared <- "/Volumes/private/studydata/data_raw"
          path_lab_support <- "/Volumes/toolboxes/lab_support"}
        )
```


Packages for lab workflow 
```{r, packages_workflow, message=FALSE, warning=FALSE}

library(conflicted) # detect and warn about function conflicts
conflict_prefer("filter", "dplyr")

library(here)  # establish project directory consistently as working directory
```

Relative Paths 
```{r}
path_log <- "shared/notes"
```


Packages for script
```{r, packages_script, message=FALSE, warning=FALSE}

# for data wrangling
library(tidyverse)  # always need this
library(rsample)
library(janitor)

library(purrr)
library(readx)
```



Functions
```{r}
import_w_subid <- function(xlsxfile){
  read_excel(xlsxfile) %>% 
    mutate(subid = str_extract(xlsxfile, "\\d\\d\\d"))
}

merge_raw_files <- function(file_suffix) {
  list.files(file.path(path_raw), 
           recursive = TRUE,
           pattern = paste0("\\d\\d\\d_", file_suffix, ".xlsx"),
           full.names = TRUE) %>% 
  as.list() %>% 
  set_names(str_extract(., "\\d\\d\\d")) %>% 
  map_df(~import_w_subid(.x) %>% 
           clean_names() %>% 
           mutate(across(everything(), as.character)))
}
```


### Import locations files
Import
```{r}
known_locations <- merge_raw_files("Locations") %>% 
  glimpse()
```


```{r}
list.files(file.path(path_raw), 
           recursive = TRUE,
           pattern = paste0("\\d\\d\\d_", file_suffix, ".xlsx"),
           full.names = TRUE) %>% 
  as.list() %>% 
  set_names(str_extract(., "\\d\\d\\d")) %>% 
  map_df(~import_w_subid(.x) %>% 
           clean_names() %>% 
           mutate(across(everything(), as.character)))
```




### Save final shared file

# FIX: This is a temp save b/c JJC needs this file.   We still need to do EDA before trusting these data!
```{r}
# known_locations %>% 
#   select(subid, utc, street_address, city, state, type, drank, alcohol, emotion, risk, avoid, vacation, lat, long) %>%   #added by JJC b.c of prob with extra columns
#   write_csv(file.path(path_shared, "locations.csv"))
```
