make_rset <- function(train_ids, d) {

# makes manual rset based on train subids generated by GA Tech
# train_ids is a df with subids for each training fold in separate columns
# code assumes that all subids are assigned to either train or test for each split
# d is df with all X and Y
# returns an rset
  make_split_list <- function(train_ids, d) {
    train_ids <- unlist(train_ids)
    d <- d %>% 
      mutate(index = row_number())
    
    train_indices <- d %>% 
      filter(subid %in% train_ids) %>% 
      pull(index)
    
    # put all other indices in test
    test_indices <- d %>% 
      filter(!(subid %in% train_ids)) %>% 
      pull(index)
    
    return(list(analysis = train_indices, assessment = test_indices))
  }
  
  indices <- train_ids %>% 
    map(~make_split_list(., d))
  
  splits <- lapply(indices, make_splits, data = d)
  rset <- manual_rset(splits, str_c("split ", 1:ncol(train_ids)))
  
  return(rset)
}
