---
format: revealjs
---

<!-- Need title page-->

---
## Mental Healthcare Needs are High and Unmet

<!--need to space the first and second sets of bullet points a bit more--> 
- In 2019, 52 million Americans had an active mental illness
  - More than half did not receive any treatment


- 20 million adults had an active substance use disorder
  - 9 out of 10 did not receive any treatment


::: {.notes}
We have a mental health crisis in the U.S. and it is a crisis of unmet high need because our delivery of mental healthcare is deeply flawed. In 2019, more than half of the 52 million Americans with an active mental illness did not receive any treatment. More than half!

[PAUSE] And for the 20 million adults suffering with a substance use disorder, it was worse still; 9 out of 10 without any treatment

:::


## Mental Healthcare Needs are High and Unmet

<!--need to make the first two sets of points gray on this slide to highlight the third point-->

- In 2019, 52 million Americans had an active mental illness
  - More than half did not receive any treatment


- 20 million adults had an active substance use disorder
  - 9 out of 10 did not receive any treatment
  
  
- Large treatment disparities exist by race, ethnicity, geography, and income



::: {.notes}
Our failure to treat is even more troubling for vulnerable groups.  Black and LatinX adults receive mental healthcare services at only half the rate of whites.  

And similar mental healthcare disparities exist for people living in rural communities and for those with lower incomes.
:::

## Mental Healthcare Needs are High and Unmet


- In 2019, 52 million Americans had an active mental illness
  - More than half did not receive any treatment


- 20 million adults had an active substance use disorder
  - 9 out of 10 did not receive any treatment
  
  
- Large treatment disparities exist by race, ethnicity, geography, and income


- Failure to treat is not surprising given many treatment barriers:
  - Access
  - Availability
  - Affordability
  - Acceptability

::: {.notes}
Our failure to treat is, unfortunately, not surprising.  There are many well known barriers to receiving traditional mental healthcare.

These include problems with access that are particularly limiting for people living in rural communities

Problems with availability

Treatment costs are often prohibitive for those without health insurance 

and stigma and related issues make traditional treatments for mental illness less acceptable to some patients.  
:::

## Digital Therapeutics (DTx)

Digital therapeutics are smartphone "apps" that are designed to prevent, manage, or treat disease, including mental illness. 


Can augment mental health services to address barriers
- Accessible everywhere
- Available 24/7
- Highly scalable (affordable?)

::: {.notes}
Fortunately, digital therapeutics are now being developed and used by patients to address many of these treatment barriers.

These digital therapeutics can be combined with traditional treatments to reduce barriers because they are

-Accessible everywhere
-Available everyday, 24/7
-and highlighly scalable, which may lower costs
:::

## Digital Therapeutics (DTx)

Digital therapeutics are smartphone "apps" that are designed to prevent, manage, or treat disease, including mental illness. 


Can augment mental health services to address barriers
- Accessible everywhere
- Available 24/7
- Highly scalable (affordable?)
- Effective! <!--Need to make above points gray-->

::: {.notes}
Of course, these benefits would be meaningless if digital therapeutics were not effective.

But they are.  

For example, patients with substance use disorders who use a digital therapeutic have almost double the odds of being abstinent from alcohol or other drugs

These increases in abstinence from using digital therapeutics are observed not only when compared to patients on wait lists, who have yet to gain access to treatment but also when digital therapeutics are added on top of traditional treatments for substance use disorders.

And these benefits are durable - they have been documented up to 12 months after the start of treatment.  
:::
