---
title: "Basic Shell for Rmd in Curtin Lab (last update: 12/15/2020)"
author: "John Curtin"
date: "`r format(Sys.time(), "%Y-%m-%d")`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
---
```{css, include = FALSE}
pre, code {
  max-height: 500px;
  overflow-y: auto;
  white-space: pre !important; 
  overflow-x: auto
  # all codeblocks bigger than 500 px will be scrollable - can adjust as needed 
  # all codeblocks wider then 100% will be scollable - can make narrower with max-width: 50% or similar 
}
```

### Notes
Purpose: Briefly describe goal of the script.   

Inputs:

* Input 1
* Input 2

Outputs

* Output 1
* Output 2

### Setup
```{r setup, include = FALSE}
knitr::opts_chunk$set()
```


Paths 
```{r}
# Path variables should start with path_ so that they are easy to auto-complete
```

Packages and Source
```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(tidymodels)
library(janitor)
library(kableExtra)
library(ggthemes)

```


### First Processing/Analysis Section
