---
title: "make enriched gps/location"
author: "John Curtin"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = dplyr::if_else(Sys.info()[["sysname"]] == "Windows",
      "P:/studydata/risk/knits/gps", 
      "/Volumes/private/studydata/risk/knits/gps")
    )
  })
---

### Code Status

under development

### Notes   



### Set Up Environment

Absolute paths
```{r, absolute paths}
switch (Sys.info()[['sysname']],
        # PC paths
        Windows = {
          path_shared <- "P:/studydata/risk/data_processed/shared"
          path_gps <- "P:/studydata/risk/data_processed/gps"},

        # IOS paths
        Darwin = {
          path_shared <- "/Volumes/private/studydata/risk/data_processed/shared"
          path_gps <- "/Volumes/private/studydata/risk/data_processed/gps"}
        )
```

Packages for lab workflow 
```{r, packages_workflow, message=FALSE, warning=FALSE}
library(conflicted) # detect and warn about function conflicts
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")

library(here)  # establish project directory consistently as working directory
```


Packages for script
```{r, packages_script, message=FALSE, warning=FALSE}
# for data wrangling
library(tidyverse)
library(vroom)
library(purrr)
library(furrr)
library(janitor)
```


Source for script
```{r, source_script, message=FALSE, warning=FALSE}
source(here("../lab_support/fun_gps.R"))
```


### Begin Main Code

Open data files
```{r}
gps <-  vroom(here(path_shared, "gps.csv")) %>% 
  glimpse()

locs <- vroom(here(path_shared, "locations.csv")) %>% 
  mutate(subid = as.numeric(subid)) %>% 
  select(subid, context_id, lat, lon, type, drank, alcohol, emotion, risk, avoid, 
         vacation, full_address)

```

Merge context into gps
```{r}

#enrich gps with context for one subid
enrich_subid <- function(a_subid, gps, locs) {
  gps <- gps %>% 
    filter(subid == a_subid)
  
  locs <- locs %>% 
    filter(subid == a_subid)
  
  enriched <- gps %>% 
    bind_cols(map2_dfr(gps$lon, gps$lat, find_nearest_context, context = locs)) 
  
  return(enriched)
}

#get all subids
subids <- gps %>% 
  pull(subid) %>% 
  unique() %>% 
  print()

#future_map over subids
(n_core <- parallel::detectCores(logical = FALSE))
plan(multisession, workers = n_core)

enriched <- subids %>% 
  future_map_dfr(enrich_subid, gps = gps, locs = locs) %>% 
  left_join(locs, by = c("subid", "context_id")) %>% 
  select(-lat.y, -lon.y, -accuracy, -speed_kmh, -altitude_meters, -direction,
         -data_type) %>% 
  rename(lat = lat.x, lon = lon.x) %>% 
  relocate(subid)
```


###  Brief EDA

```{r}
enriched %>%  
  glimpse

enriched %>% 
  tabyl(subid)

enriched %>% 
  pull(subid) %>% 
  unique %>% 
  length
```

```{r}
enriched %>% 
  summarize(across(.fns = ~sum(is.na(.))))
```


### Save enriched GPS
Saving compressed for use on CHTC for feature engineering

```{r}
enriched %>% 
  vroom_write(here(path_gps, "gps_enriched.csv", delim = ","))
```