---
title: "Reliability of self-report items"
author: "Kendra Wyant"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: 
  html_document:
    toc: true 
    toc_depth: 4
---

### Setup
```{css, echo = FALSE}
pre, code {
  max-height: 500px;
  overflow-y: auto;
  white-space: pre !important; 
  overflow-x: auto
}
```

Paths 
```{r}
path_burden <- "/Volumes/private/StudyData/RISK/analysis/burden/data"
```

Packages and Source
```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(kableExtra)
```

### Read in data
```{r}
burden <- read_csv(file.path(path_burden, "burden.csv"), col_types = cols()) %>% 
  # wristband will be analyzed in supplemental - not enough observations
  select(-contains("wristband"))

# pull out last available sleep monitor data since this date will be earlier than last survey date for some
burden_sleep <- burden %>% 
  filter(!is.na(sleep_interfere)) %>% 
  group_by(subid) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  select(c(subid, starts_with("sleep_")))
  
# pull out most recent survey for each subid
burden_last <- burden %>% 
  select(-c(starts_with("sleep_"))) %>% 
  group_by(subid) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  # join with sleep data
  full_join(burden_sleep, by = c("subid")) %>% 
  glimpse()
```



### Chronbachs alpha for 3 self-report items

Create composites   
```{r}
burden_composites <- burden_last %>% 
  group_by(subid) %>% 
  summarise(interference = mean(c(daily_survey_interfere, audio_checkin_interfere, carrying_phone_interfere,
                       sleep_interfere), na.rm = TRUE),
            dislike = mean(c(daily_survey_dislike, audio_checkin_dislike, carrying_phone_dislike,
                       location_dislike, sms_content_dislike, all_logs_dislike, sleep_dislike), na.rm = TRUE),
            willingness = mean(c(daily_survey_4_1year, audio_checkin_1year, carrying_phone_1year,
                       sleep_1year, location_1year, all_logs_1year, sms_content_1year), na.rm = TRUE)) 
burden_composites %>% 
  print(n = Inf)
```

Get alpha
```{r}
burden_composites %>% 
  select(-subid) %>% 
  psych::alpha()

burden_composites %>% 
  select(-subid) %>% 
  cor()
```

<br>

### Self-report items - consistency within measure
```{r}
interference <- burden_last %>% 
  select(contains("interfere"))
dislike <- burden_last %>% 
  select(contains("dislike"))
willingness <- burden_last %>% 
  select(contains("1year"))
```

interference
```{r}
burden_last %>% 
  select(names(interference)) %>% 
  psych::alpha()

burden_last %>% 
  select(names(interference)) %>% 
  cor(use = "pairwise.complete.obs") %>% 
  round(2)
```

dislike
```{r}
burden_last %>% 
  select(names(dislike)) %>% 
  psych::alpha()

burden_last %>% 
  select(names(dislike)) %>% 
  cor(use = "pairwise.complete.obs") %>% 
  round(2)
```

willingness
```{r}
burden_last %>% 
  select(names(willingness)) %>% 
  psych::alpha()

burden_last %>% 
  select(names(willingness)) %>% 
  cor(use = "pairwise.complete.obs") %>% 
  round(2)
```


<br>
