---
output: pdf_document
---

Dear Dr. Wright, 

We are pleased to submit our original manuscript “Machine learning models for temporally precise lapse prediction in alcohol use disorder” for your review at Journal of Psychopathology and Clinical Science. Given the transparency, rigor, and potential for impact of our study and report, we believe this is an excellent fit for the journal. Specifically, it is an empirical paper in which we develop, evaluate, and contextualize three models that predict probabilities of a future lapse back to alcohol use with increasing temporal precision. We use ecological momentary assessment (EMA) methods to collect longitudinal in situ measures of relapse prevention constructs. Moreover, we use the most rigorous machine learning methods available (grouped, nested, k-fold cross-validation) to evaluate how well our models generalize to new people.

One publication exists from the larger grant-funded parent project containing this dataset. In this paper we only report on compliance, acceptability measures, and qualitative data related to EMA. No prediction aims were included and no EMA constructs were analyzed. Therefore, this manuscript contains entirely original analyses. We have posted the manuscript in its current form as a pre-print at PsyArXiv [https://osf.io/preprints/psyarxiv/cgsf7/](https://osf.io/preprints/psyarxiv/cgsf7/). The manuscript has not been posted on any other website. All data and materials have been made publicly available and can be accessed at [https://osf.io/w5h9y/](https://osf.io/w5h9y/). 

All authors and contributors complied with the APA ethical standards in our treatment of participants during the course of this research study, and all study procedures were approved by the University of Wisconsin-Madison Institutional Review Board. The authors do not have any conflicts of interest to report regarding the submitted work.

We are submitting this article for review as a “Regular Article”. The manuscript has been prepared in accordance with APA style, 7th edition. Specific information about manuscript length and components is as follows:
•	Overall manuscript length: 8,714 words <!--confirm final word count prior to submission-->
•	Number of tables: 2
•	Number of figures: 3
•	Supplemental materials: Yes (one supplemental document; includes a transparency report, supplemental methods, and 5 supplemental figures)

The corresponding author is:
John J. Curtin, Ph.D.
Department of Psychology
University of Wisconsin-Madison
1202 West Johnson St
Madison, WI 53706
EMAIL: jjcurtin@wisc.edu 
PH: 608-262-0387
FAX: 608-262-4029

If we can provide any additional information that would be of assistance, please do not hesitate to ask. We look forward to hearing from you regarding this manuscript.

Sincerely,
Kendra Wyant, Sarah J. Sant'Ana, Gaylen E. Fronk, & John J. Curtin

