---
title: "Makes clean database files"
author: "John Curtin"
date: "4/4/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

##Setup 
```{r setup, include = FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
#install.packages("P:/Documentation/Software/R/lmSupport/Source/lmSupport.tar.gz", repos = NULL, type = "source")
library(stringr)
library(lmSupport)
library(readxl)

source(file.path("./shared/scripts_make", "fun_database.R")) 

in_path <-  "P:/StudyData/RISK/raw_data"
out_path <- "P:/StudyData/RISK/database"
```


##Select subjects to reduce
Set n_subids to "ALL", "UPDATE", "166+", or vector of numeric SubIDs if we want to reduce a subset of SubIDs

```{r}
n_subids <- "ALL"

#if "ALL", Get all SubIDs
if(length(n_subids) == 1 && toupper(n_subids) == "ALL"){
  n_subids <- list.dirs(path = in_path, full.names = FALSE, recursive = FALSE)
  n_subids <- suppressWarnings(as.numeric(n_subids))
  n_subids <- subset(n_subids,!is.na(n_subids))
  
  #Delete and re-establish database
  message("Deleting database at:", out_path)
  unlink(out_path, recursive = TRUE)
  dir.create(out_path)
}

#if "+", reduce all subject from subId and greater
if(length(n_subids) == 1 && str_detect(n_subids, "\\+")){
  start_id <- as.numeric(str_sub(n_subids, 1, str_length(n_subids)-1))
  all_subids <- list.dirs(path = in_path, full.names = FALSE, recursive = FALSE)
  all_subids <- suppressWarnings(as.numeric(all_subids))
  all_subids <- subset(all_subids,!is.na(all_subids))
  n_subids <- all_subids[all_subids >= start_id]
}

#if "UPDATE, Get SubIDs whose most recent database files were created before their final visit or never
if(length(n_subids) == 1 && toupper(n_subids) == "UPDATE" ){
  n_subids <- list.dirs(path = in_path, full.names = FALSE, recursive = FALSE)
  n_subids <- suppressWarnings(as.numeric(n_subids))
  n_subids <- subset(n_subids,!is.na(n_subids))?
  
  ReduceFolders <- as.numeric(list.dirs(path = out_path, full.names = FALSE, recursive = FALSE))

  i <- 1
  while (i < length(n_subids)){
    message("Checking: ", n_subids[i])
    if(!(n_subids[i] %in% ReduceFolders)){
      message("...REDUCE")
      i <- i + 1 #sub needs reducing; skip to next
    }else{
      str_subid <- varPadString(n_subids[i],3)
      dVisits <- read_excel(file.path(in_path, str_subid, str_c(str_subid, "_VisitDates.xlsx")), na = c("", "NA"))
      if(!is.na(dVisits$FinalVisit)){
        final_visit <- as.Date(dVisits$FinalVisit) + days(1)
      }else{
        final_visit <- as.Date(dVisits$EndStudy) + days(1)
      }
      
      reduce_date <- as.Date(file.mtime(file.path(out_path, str_subid, str_c(str_subid, "_VisitDates.rds"))))
      if(reduce_date < final_visit){
        message("...REDUCE")
        i <- i + 1 #sub needs reducing, skip to next
      }else{
        message("...SKIP")
        n_subids <- n_subids[-i]
      }
    }
  }
}

message("SubIDs to reduce:")
n_subids
```


## Subject looping

$download\_surveys$ is set to false because we have downloaded final copies of all surveys; see $download\_qualtrics()$
```{r}
download_surveys <- FALSE 
add_aggregate_data <- TRUE
for (a_subid in n_subids){
  add_subject_to_database(a_subid, download_surveys, add_aggregate_data)
  download_surveys <- FALSE       #only true for first SubID
  add_aggregate_data <- FALSE  #only true for first SubID
}
 
#clean the database files
source(file.path("./shared/scripts_make", "cln_database.R"))
```
