---
title: "Acceptability Results"
author: "Kendra Wyant"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: html_document
---

Purpose: These are the primary analyses for the acceptability of personal sensing measures paper. 

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.kable.NA = '')
```

```{css, echo = FALSE}
pre, code {
  max-height: 500px;
  overflow-y: auto;
  white-space: pre !important; 
  overflow-x: auto
}
```

```{r}
path_burden <- "/Volumes/private/studydata/risk/analysis/burden/data"
path_data <- "/Volumes/private/studydata/risk/analysis/shared/data"
```


```{r message = FALSE}
library(tidyverse)
library(kableExtra)
library(janitor)
library(ggtext)
library(cowplot)
library(ggstatsplot)
library(patchwork)
library(knitr)
```

```{r}
# function for adding Y label - code from Stack overflow
add_global_label <- function(pwobj, Xlab = NULL, Ylab = NULL, Xgap = 0.03, Ygap = 0.03, ...) {
  ylabgrob <- patchwork::plot_spacer()
  if (!is.null(Ylab)) {
    ylabgrob <- ggplot() +
      geom_text(aes(x = 1, y = 1), label = Ylab, angle = 90, family = "Times New Roman", size = 4.5) +
      theme_void() 
  }
  if (!is.null(Xlab)) {
    xlabgrob <- ggplot() +
      geom_text(aes(x = .5, y = .5), label = Xlab) +
      theme_void() 
  }
  if (!is.null(Ylab) & is.null(Xlab)) {
    return((ylabgrob + patchworkGrob(pwobj)) + 
             patchwork::plot_layout(widths = 100 * c(Ygap, 1 - Ygap)))
  }
  if (is.null(Ylab) & !is.null(Xlab)) {
    return((ylabgrob + pwobj) + 
             (xlabgrob) +
             patchwork::plot_layout(heights = 100 * c(1 - Xgap, Xgap),
                                    widths = c(0, 100),
                                    design = "
                                   AB
                                   CC
                                   "
             ))
  }
  if (!is.null(Ylab) & !is.null(Xlab)) {
    return((ylabgrob + pwobj) + 
             (xlabgrob) +
             patchwork::plot_layout(heights = 100 * c(1 - Xgap, Xgap),
                                    widths = 100 * c(Ygap, 1 - Ygap),
                                    design = "
                                   AB
                                   CC
                                   "
             ))
  }
  return(pwobj)
}
```

<br>


##### Participant characteristics

```{r}
screen <- read_csv(file.path(path_data, "screen.csv"), col_types = cols()) 
visit_dates <- read_csv(file.path(path_data,"visit_dates.csv"), col_types = cols())

# include only enrolled participants (n = 169) - use visit dates
sample_intake <- visit_dates %>% 
  filter(!(is.na(start_study))) %>% 
  filter(start_study != end_study) 
screen <- screen %>% 
  filter(subid %in% sample_intake$subid)
```

```{r}
# create demographic tibble for table
dem <- screen %>% 
  summarise(mean = as.character(round(mean(dem_1, na.rm = TRUE), 1)),
            SD = as.character(round(sd(dem_1, na.rm = TRUE), 1))) %>% 
  mutate(var = "Age",
         n = as.numeric(""),
         perc = as.numeric("")) %>% 
  select(var, n, perc, everything()) %>% 
  full_join(screen %>% 
  select(var = dem_2) %>% 
  group_by(var) %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / sum(n)) * 100)) %>% 
  full_join(screen %>% 
  select(var = dem_3) %>% 
  mutate(var = fct_relevel(factor(var, 
                         c("American Indian/Alaska Native", "Asian", "Black/African American",
                           "White/Caucasian", "Other/Multiracial")))) %>%
  group_by(var) %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / sum(n)) * 100)) %>% 
  full_join(screen %>% 
  select(var = dem_4) %>% 
  mutate(var = case_when(var == "No, I am not of Hispanic, Latino, or Spanish origin" ~ "No",
                         TRUE ~ "Yes"),
         var = fct_relevel(factor(var, c("Yes", "No")))) %>% 
  group_by(var) %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / sum(n)) * 100)) %>% 
  full_join(screen %>% 
  select(var = dem_5) %>% 
  mutate(var = fct_relevel(factor(var, 
                         c("Less than high school or GED degree", "High school or GED", 
                           "Some college", "2-Year degree", "College degree", "Advanced degree")))) %>%
  group_by(var) %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / sum(n)) * 100)) %>% 
  full_join(screen %>% 
  select(var = dem_6, dem_6_1) %>% 
  mutate(var = case_when(dem_6_1 == "Full-time" ~ "Employed full-time",
                         dem_6_1 == "Part-time" ~ "Employed part-time",
                         TRUE ~ var)) %>% 
  mutate(var = fct_relevel(factor(var, 
                         c("Employed full-time", "Employed part-time", "Full-time student",
                           "Homemaker", "Disabled", "Retired", "Unemployed", 
                           "Temporarily laid off, sick leave, or maternity leave",
                           "Other, not otherwise specified")))) %>%
  group_by(var) %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / sum(n)) * 100)) %>% 
  full_join(screen %>% 
  summarise(mean = as.character(round(mean(dem_7, na.rm = TRUE), 0)),
            SD = as.character(round(sd(dem_7, na.rm = TRUE), 0))) %>% 
  mutate(var = "Income",
        n = as.numeric(""),
        perc = as.numeric("")) %>% 
  select(var, n, perc, everything())) %>% 
  full_join(screen %>% 
  select(var = dem_8) %>% 
  mutate(var = case_when(var == "Never Married" ~ "Never married",
                         TRUE ~ var)) %>% 
  mutate(var = fct_relevel(factor(var, 
                         c("Never married", "Married", "Divorced", "Separated",
                           "Widowed")))) %>%
  group_by(var) %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / sum(n)) * 100))
```

```{r}
# display and format table
dem %>% 
  kbl(col.names = c("", "<i>n</i>", "%", "<i>M</i>", "<i>SD</i>"),
      digits = 1,
      align = c("l", "c", "c", "c", "c"),
      caption = "<b>Table 2</b><br><br><i>Demographics for all enrolled participants (N = 169)</i>",
      table.attr = "style='width:60%;'",
      escape = FALSE) %>% 
  row_spec(row = 0, align = "c") %>% 
  kable_classic(html_font = "Times New Roman", position = "left") %>% 
  pack_rows("Sex", 2, 3, bold = FALSE) %>% 
  pack_rows("Race", 4, 8, bold = FALSE) %>% 
  pack_rows("Hispanic, Latino, or Spanish Origin", 9, 10, bold = FALSE) %>% 
  pack_rows("Education", 11, 16, bold = FALSE) %>% 
  pack_rows("Employment", 17, 25, bold = FALSE) %>% 
  pack_rows("Marital Status", 27, 31, bold = FALSE)
```

```{r}
# create alcohol use history tibble for table
auh <- screen %>% 
  summarise(mean = mean(auh_1, na.rm = TRUE),
            SD = sd(auh_1, na.rm = TRUE)) %>% 
  mutate(var = "Age of first drink",
        n = as.numeric(""),
        perc = as.numeric("")) %>% 
  select(var, n, perc, everything()) %>% 
  full_join(screen %>% 
  summarise(mean = mean(auh_2, na.rm = TRUE),
            SD = sd(auh_2, na.rm = TRUE)) %>% 
  mutate(var = "Age of regular drinking",
        n = as.numeric(""),
        perc = as.numeric("")) %>% 
  select(var, n, perc, everything())) %>% 
  full_join(screen %>% 
  summarise(mean = mean(auh_3, na.rm = TRUE),
            SD = sd(auh_3, na.rm = TRUE)) %>% 
  mutate(var = "Age at which drinking became problematic",
        n = as.numeric(""),
        perc = as.numeric("")) %>% 
  select(var, n, perc, everything())) %>% 
  full_join(screen %>% 
  summarise(mean = mean(auh_4, na.rm = TRUE),
            SD = sd(auh_4, na.rm = TRUE)) %>% 
  mutate(var = "Age of first quit attempt",
        n = as.numeric(""),
        perc = as.numeric("")) %>% 
  select(var, n, perc, everything())) %>% 
  full_join(screen %>% 
  summarise(mean = mean(auh_5, na.rm = TRUE),
            SD = sd(auh_5, na.rm = TRUE)) %>% 
  mutate(var = "Number of Quit Attempts",
        n = as.numeric(""),
        perc = as.numeric("")) %>% 
  select(var, n, perc, everything())) %>% 
  full_join(screen %>% 
  select(var = auh_6_1) %>%
  mutate(var = case_when(var == "Long-Term Residential Treatment (more than 6 months)" ~ "Long-term residential (6+ mos.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = auh_6_2) %>%
  mutate(var = case_when(var == "Short-Term Residential Treatment (less than 6 months)" ~ "Short-term residential (< 6 mos.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = auh_6_3) %>%
  mutate(var = case_when(var == "Outpatient Treatment" ~ "Outpatient",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = auh_6_4) %>%
  mutate(var = case_when(var == "Individual Counseling" ~ "Individual counseling",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = auh_6_5) %>%
  mutate(var = case_when(var == "Group Counseling" ~ "Group counseling",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = auh_6_6) %>%
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = auh_6_7) %>%
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = auh_7) %>% 
  mutate(var = fct_relevel(factor(var, c("Yes", "No")))) %>%
  group_by(var) %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / sum(n)) * 100)) %>% 
  full_join(screen %>% 
  mutate(across(dsm5_1:dsm5_11, ~ recode(., "No" = 0, "Yes" = 1))) %>% 
  rowwise() %>% 
  # calculate dsm5 score by adding up dsm5_1 through dsm5_11
  mutate(dsm5_total = sum(c(dsm5_1, dsm5_2, dsm5_3, dsm5_4, dsm5_5, dsm5_6, dsm5_7, 
                            dsm5_8, dsm5_9, dsm5_10, dsm5_11))) %>% 
  ungroup() %>% 
  summarise(mean = mean(dsm5_total),
            SD = sd(dsm5_total)) %>% 
  mutate(var = "AUD DSM-5 Symptom Count*",
        n = as.numeric(""),
        perc = as.numeric("")) %>% 
  select(var, n, perc, everything())) %>% 
  full_join(screen %>% 
  select(var = assist_1_1) %>%
  filter(var == "Yes") %>% 
  mutate(var = case_when(var == "Yes" ~ "Tobacco products (cigarettes, chewing tobacco, cigars, etc.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = assist_1_2) %>%
  filter(var == "Yes") %>% 
  mutate(var = case_when(var == "Yes" ~ "Cannabis (marijuana, pot, grass, hash, etc.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = assist_1_3) %>%
  filter(var == "Yes") %>% 
  mutate(var = case_when(var == "Yes" ~ "Cocaine (coke, crack, etc.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = assist_1_4) %>%
  filter(var == "Yes") %>% 
  mutate(var = case_when(var == "Yes" ~ "Amphetamine type stimulants (speed, diet pills, ecstasy, etc.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = assist_1_5) %>%
  filter(var == "Yes") %>% 
  mutate(var = case_when(var == "Yes" ~ "Inhalants (nitrous, glue, petrol, paint thinner, etc.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = assist_1_6) %>%
  filter(var == "Yes") %>% 
  mutate(var = case_when(var == "Yes" ~ "Sedatives or sleeping pills (Valium, Serepax, Rohypnol, etc.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = assist_1_7) %>%
  filter(var == "Yes") %>% 
  mutate(var = case_when(var == "Yes" ~ "Hallucinogens (LSD, acid, mushrooms, PCP, Special K, etc.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) %>% 
  full_join(screen %>% 
  select(var = assist_1_8) %>%
  filter(var == "Yes") %>% 
  mutate(var = case_when(var == "Yes" ~ "Opioids (heroin, morphine, methadone, codeine, etc.)",
                         TRUE ~ var)) %>% 
  group_by(var) %>% 
  drop_na() %>% 
  summarise(n = n()) %>% 
  mutate(perc = (n / 154) * 100)) 
```

<br>

```{r}
# display and format table
auh %>%
  kbl(col.names = c("", "<i>n</i>", "%", "<i>M</i>", "<i>SD</i>"),
      digits = 1,
      align = c("l", "c", "c", "c", "c"),
      caption = "<b>Table 3</b><br><br><i>Alcohol-related charicterizations for all enrolled participants (N = 169)</i>",
      table.attr = "style='width:70%;'",
      escape = FALSE) %>% 
  row_spec(row = 0, align = "c") %>% 
  kable_classic(html_font = "Times New Roman", position = "left") %>% 
  pack_rows("AUD Milestones", 1, 4, bold = FALSE) %>% 
  pack_rows("Types of Treatment", 6, 12, bold = FALSE) %>% 
  pack_rows("Received Medication for AUD", 13, 14, bold = FALSE) %>% 
  pack_rows("Lifetime Drug Use", 16, 23, bold = FALSE) %>% 
  footnote("*AUD DSM-5 symptom count was documented through self-report and not a clinical interview.")
```

<br>


#### Self-report measures of acceptability

```{r}
burden <- read_csv(file.path(path_burden, "burden.csv"), col_types = cols()) %>% 
  # wristband will be analyzed in supplemental - not enough observations
  select(-contains("wristband"))

# pull out last available sleep monitor data since this date will be earlier than last survey date for some
burden_sleep <- burden %>% 
  filter(!is.na(sleep_interfere)) %>% 
  group_by(subid) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  select(c(subid, starts_with("sleep_")))
  
# pull out most recent survey for each subid
burden_last <- burden %>% 
  select(-c(starts_with("sleep_"))) %>% 
  group_by(subid) %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% 
  ungroup() %>% 
  # join with sleep data
  full_join(burden_sleep, by = c("subid"))
```

##### Interference
```{r warning = FALSE, fig.height = 6}
burden_plot_int <- burden_last %>% 
  select(contains("interfere")) %>%   
  pivot_longer(everything(), "measure", values_drop_na = TRUE) %>% 
  mutate(measure = factor(measure, 
                          levels = c("audio_checkin_interfere", "daily_survey_interfere", 
                                     "sleep_interfere", "carrying_phone_interfere"),
                          labels = c("Audio Check-in", "Daily Survey (x4)", "Sleep Monitor", "Carrying Phone"))) %>% 
  mutate(value = factor(value, levels = c(-2:2), labels = c("strongly disagree", "disagree", "undecided", "agree", "strongly agree"))) %>% 
  mutate(active = case_when(measure == "Audio Check-in" ~ "Active",
                            measure == "Daily Survey (x4)" ~ "Active",
                            measure == "Sleep Monitor" ~ "Active")) 

active <- burden_plot_int %>% 
  filter(measure == "Audio Check-in" | measure == "Daily Survey (x4)" | measure == "Sleep Monitor") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#E7F8FF") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = "Proportion",
       x = NULL) +
  theme(legend.position = "none",
        text = element_text(family = "Times New Roman"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = "undecided"), linetype = "dashed", size = .3) +
  geom_vline(aes(xintercept = means), burden_plot_int %>% 
  filter(measure == "Audio Check-in" | measure == "Daily Survey (x4)" | measure == "Sleep Monitor") %>% 
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .4) +
  theme(text = element_text(size = 14))


active
```

save image
```{r}
# ggsave(plot = active,  "~/Desktop/interfere.png", width = 6.5, height = 5, units = "in", device = "png",  dpi = 1000)
```


##### Dislike
```{r message = FALSE, warning = FALSE, fig.height = 6}
burden_plot_dis <- burden_last %>% 
  select(contains("dislike")) %>%  
  pivot_longer(everything(), "measure", values_drop_na = TRUE) %>% 
   mutate(measure = factor(measure, 
                          levels = c("audio_checkin_dislike", "daily_survey_dislike", "sleep_dislike",
                                     "location_dislike", "all_logs_dislike", "sms_content_dislike"),
                          labels = c("Audio Check-in", "Daily Survey (x4)", "Sleep Monitor",
                                     "Location", "Logs (SMS/voice)", "SMS Content"))) %>% 
  mutate(value = factor(value, levels = c(-2:2), labels = c("strongly disagree", "disagree", "undecided", "agree", "strongly agree"))) %>% 
  mutate(active = case_when(measure == "Audio Check-in" ~ "Active",
                            measure == "Daily Survey (x4)" ~ "Active",
                            measure == "Sleep Monitor" ~ "Active",
                            measure == "Location" ~ "Passive",
                            measure == "Logs (SMS/voice)" ~ "Passive",
                            measure == "SMS Content" ~ "Passive")) 

active_dis <- burden_plot_dis %>% 
  filter(measure == "Audio Check-in" | measure == "Daily Survey (x4)" | measure == "Sleep Monitor") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#E7F8FF") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = NULL,
       x = NULL) +
  theme(legend.position = "none",
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text = element_text(family = "Times New Roman")) +
  ylim(0, .65) +
  geom_vline(aes(xintercept = means), burden_plot_dis %>% 
  filter(measure == "Audio Check-in" | measure == "Daily Survey (x4)" | measure == "Sleep Monitor") %>% 
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .4) +
  geom_vline(aes(xintercept = "undecided"), linetype = "dashed", size = .3) +
  theme(text = element_text(size = 12))


passive_dis <- burden_plot_dis %>% 
  filter(measure == "Location" | measure == "Logs (SMS/voice)" | measure == "SMS Content") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#F2EFFF") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = NULL,
       x = NULL) +
    theme(legend.position = "none",
        text = element_text(family = "Times New Roman", size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = means), burden_plot_dis %>% 
  filter(measure == "Location" | measure == "Logs (SMS/voice)" | measure == "SMS Content") %>%  
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .4) +
  geom_vline(aes(xintercept = "undecided"), linetype = "dashed", size = .3) 

dislike_final_plot <- wrap_plots(active_dis, passive_dis, ncol = 1)

dislike_final_plot <- dislike_final_plot  %>% 
  add_global_label(Ylab = "                   Proportion",
                   Ygap = .02
)

dislike_final_plot
```

save image
```{r message = FALSE}
# export saved as 725 x 550
# ggsave(plot = dislike_final_plot,  "~/Desktop/dislike.png", width = 8, height = 7, units = "in", device = "png",  dpi = 1000)
```

##### Willingness to Continue

```{r message = FALSE, warning = FALSE, fig.height = 6}
burden_plot_1yr <- burden_last %>% 
  select(contains("1year")) %>%  
  pivot_longer(everything(), "measure", values_drop_na = TRUE) %>% 
  mutate(measure = factor(measure, 
                          levels = c("audio_checkin_1year", "daily_survey_4_1year", 
                                     "daily_survey_1_1year", "sleep_1year", "location_1year", 
                                     "all_logs_1year", "sms_content_1year"),
                          labels = c("Audio Check-in", "Daily Survey (x4)", "Daily Survey (x1)<i><sup>a</sup></i>",
                                     "Sleep Monitor", "Location", "Logs (SMS/voice)", "SMS Content"))) %>% 
  mutate(value = factor(value, levels = c(-2:2), labels = c("strongly disagree", "disagree", "undecided", "agree", "strongly agree"))) %>% 
  mutate(active = case_when(measure == "Audio Check-in" ~ "Active",
                            measure == "Daily Survey (x4)" ~ "Active",
                            measure == "Daily Survey (x1)<i><sup>a</sup></i>" ~ "Active",
                            measure == "Sleep Monitor" ~ "Active",
                            measure == "Location" ~ "Passive",
                            measure == "Logs (SMS/voice)" ~ "Passive",
                            measure == "SMS Content" ~ "Passive")) 

willingness_active <- burden_plot_1yr %>% 
  filter(measure == "Audio Check-in" | measure == "Daily Survey (x4)" | measure == "Sleep Monitor"
         # | measure == "Daily Survey (x1)<i><sup>a</sup></i>" 
         ) %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#E7F8FF") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = NULL,
       x = NULL) +
  theme(legend.position = "none",
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text = element_text(family = "Times New Roman", size = 12),
        strip.text = element_markdown()) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = means), burden_plot_1yr %>% 
  filter(measure == "Audio Check-in" | measure == "Daily Survey (x4)" | measure == "Sleep Monitor"
         # |  measure == "Daily Survey (x1)<i><sup>a</sup></i>"
         ) %>% 
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .4) +
  geom_vline(aes(xintercept = "undecided"), linetype = "dashed", size = .3)


willingness_passive <- burden_plot_1yr %>% 
  filter(measure == "Location" | measure == "Logs (SMS/voice)" | measure == "SMS Content") %>% 
  ggplot(aes(x = value, y = ..prop.., group = measure)) +
  geom_bar(color = "black", fill = "#F2EFFF") +
  facet_grid(active ~ measure) +
  theme_classic() +
  labs(y = NULL,
       x = NULL) +
    theme(legend.position = "none",
        text = element_text(family = "Times New Roman", size = 12),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, .6) +
  geom_vline(aes(xintercept = means), burden_plot_1yr %>% 
  filter(measure == "Location" | measure == "Logs (SMS/voice)" | measure == "SMS Content") %>%  
  group_by(measure) %>% 
  summarise(means = mean(as.numeric(value), na.rm = TRUE)), size = .4) +
  geom_vline(aes(xintercept = "undecided"), linetype = "dashed", size = .3)

willingness_final_plot <- wrap_plots(willingness_active, willingness_passive, ncol = 1)

willingness_final_plot <- willingness_final_plot  %>% 
  add_global_label(Ylab = "                   Proportion",
                   Ygap = .02
)

willingness_final_plot
```

save image
```{r message = FALSE}
# export saved as 725 x 550
# ggsave(plot = willingness_final_plot,  "~/Desktop/willingness.png", width = 8, height = 7, units = "in", device = "png",  dpi = 1000)
```


<br>

###### Regression Analyses


```{r}
# run regressions (one sample t-tests) for each measure and item
int_sl <- broom::tidy(lm(sleep_interfere ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$sleep_interfere, na.rm = TRUE),
         d = mean(burden_last$sleep_interfere, na.rm = TRUE)/sd)
int_a <-  broom::tidy(lm(audio_checkin_interfere ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$audio_checkin_interfere, na.rm = TRUE),
         d = mean(burden_last$audio_checkin_interfere, na.rm = TRUE)/sd)
int_s4 <-  broom::tidy(lm(daily_survey_interfere ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$daily_survey_interfere, na.rm = TRUE),
         d = mean(burden_last$daily_survey_interfere, na.rm = TRUE)/sd)
int_phone <-  broom::tidy(lm(carrying_phone_interfere ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$carrying_phone_interfere, na.rm = TRUE),
         d = mean(burden_last$carrying_phone_interfere, na.rm = TRUE)/sd)
dis_sl <-  broom::tidy(lm(sleep_dislike ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$sleep_dislike, na.rm = TRUE),
         d = mean(burden_last$sleep_dislike, na.rm = TRUE)/sd)
dis_a <-  broom::tidy(lm(audio_checkin_dislike ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$audio_checkin_dislike, na.rm = TRUE),
         d = mean(burden_last$audio_checkin_dislike, na.rm = TRUE)/sd)
dis_s4 <-  broom::tidy(lm(daily_survey_dislike ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$daily_survey_dislike, na.rm = TRUE),
         d = mean(burden_last$daily_survey_dislike, na.rm = TRUE)/sd)
dis_phone <- broom::tidy(lm(carrying_phone_dislike ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$carrying_phone_dislike, na.rm = TRUE),
         d = mean(burden_last$carrying_phone_dislike, na.rm = TRUE)/sd)
dis_loc <-  broom::tidy(lm(location_dislike ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$location_dislike, na.rm = TRUE),
         d = mean(burden_last$location_dislike, na.rm = TRUE)/sd)
dis_log <-  broom::tidy(lm(all_logs_dislike ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$all_logs_dislike, na.rm = TRUE),
         d = mean(burden_last$all_logs_dislike, na.rm = TRUE)/sd)
dis_sms <-  broom::tidy(lm(sms_content_dislike ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$sms_content_dislike, na.rm = TRUE),
         d = mean(burden_last$sms_content_dislike, na.rm = TRUE)/sd)
use_a <-  broom::tidy(lm(audio_checkin_1year ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$audio_checkin_1year, na.rm = TRUE),
         d = mean(burden_last$audio_checkin_1year, na.rm = TRUE)/sd)
use_sl <-  broom::tidy(lm(sleep_1year ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$sleep_1year, na.rm = TRUE),
         d = mean(burden_last$sleep_1year, na.rm = TRUE)/sd)
use_s4 <-  broom::tidy(lm(daily_survey_4_1year ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$daily_survey_4_1year, na.rm = TRUE),
         d = mean(burden_last$daily_survey_4_1year, na.rm = TRUE)/sd)
use_phone <-  broom::tidy(lm(carrying_phone_1year ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$carrying_phone_1year, na.rm = TRUE),
         d = mean(burden_last$carrying_phone_1year, na.rm = TRUE)/sd)
use_s1 <-  broom::tidy(lm(daily_survey_1_1year ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$daily_survey_1_1year, na.rm = TRUE),
         d = mean(burden_last$daily_survey_1_1year, na.rm = TRUE)/sd)
use_loc <-  broom::tidy(lm(location_1year ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$location_1year, na.rm = TRUE),
         d = mean(burden_last$location_1year, na.rm = TRUE)/sd)
use_log <-  broom::tidy(lm(all_logs_1year ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$all_logs_1year, na.rm = TRUE),
         d = mean(burden_last$all_logs_1year, na.rm = TRUE)/sd)
use_sms <-  broom::tidy(lm(sms_content_1year ~ 1, data = burden_last)) %>% 
  mutate(sd = sd(burden_last$sms_content_1year, na.rm = TRUE),
         d = mean(burden_last$sms_content_1year, na.rm = TRUE)/sd)
```


```{r}
# create three tibbles for each item to display test statistics
# interference
interfere_tbl <- burden_last %>% 
  select("Audio Check-in" = audio_checkin_interfere,
         "Daily Survey (4 times daily)" = daily_survey_interfere,
         "Sleep Monitor" = sleep_interfere) %>% 
  gather(key = "measure", value) %>%
  group_by(measure) %>% 
  select(-value) %>% 
  drop_na() %>% 
  slice(1) %>% 
  mutate(mean = case_when(measure == "Sleep Monitor" ~ int_sl$estimate,
                         measure == "Audio Check-in" ~ int_a$estimate,
                         measure == "Daily Survey (4 times daily)" ~ int_s4$estimate),
         SD = case_when(measure == "Sleep Monitor" ~ int_sl$sd,
                        measure == "Audio Check-in" ~ int_a$sd,
                        measure == "Daily Survey (4 times daily)" ~ int_s4$sd),
         t = case_when(measure == "Sleep Monitor" ~ int_sl$statistic,
                       measure == "Audio Check-in" ~ int_a$statistic,
                       measure == "Daily Survey (4 times daily)" ~ int_s4$statistic,
                       measure == "Carrying Phone" ~ int_phone$statistic),
         d = case_when(measure == "Sleep Monitor" ~ int_sl$d,
                       measure == "Audio Check-in" ~ int_a$d,
                       measure == "Daily Survey (4 times daily)" ~ int_s4$d),
         sig = case_when(measure == "Sleep Monitor" ~ int_sl$p.value,
                         measure == "Audio Check-in" ~ int_a$p.value,
                         measure == "Daily Survey (4 times daily)" ~ int_s4$p.value),
         sig = case_when(sig < .001 ~ "< .001***",
                         TRUE ~ as.character(sig))) 
# dislike
dislike_tbl <- burden_last %>% 
  select("Audio Check-in" = audio_checkin_dislike,
         "Daily Survey (4 times daily)" = daily_survey_dislike,
         "Sleep Monitor" = sleep_dislike,
         "Location" = location_dislike,
         "Logs (SMS/call)" = all_logs_dislike,
         "SMS Content" = sms_content_dislike) %>% 
  gather(key = "measure", value) %>%
  select(-value) %>% 
  group_by(measure) %>% 
  drop_na() %>% 
  slice(1) %>% 
  mutate(mean_2 = case_when(measure == "Sleep Monitor" ~ dis_sl$estimate,
                         measure == "Daily Survey (4 times daily)" ~ dis_s4$estimate,
                         measure == "Audio Check-in" ~ dis_a$estimate,
                         measure == "Location" ~ dis_loc$estimate,
                         measure == "SMS Content" ~ dis_sms$estimate,
                         measure == "Logs (SMS/call)" ~ dis_log$estimate),
       SD_2 = case_when(measure == "Sleep Monitor" ~ dis_sl$sd,
                        measure == "Daily Survey (4 times daily)" ~ dis_s4$sd,
                        measure == "Audio Check-in" ~ dis_a$sd,
                        measure == "Location" ~ dis_loc$sd,
                        measure == "SMS Content" ~ dis_sms$sd,
                        measure == "Logs (SMS/call)" ~ dis_log$sd),
        t_2 = case_when(measure == "Sleep Monitor" ~ dis_sl$statistic,
                        measure == "Daily Survey (4 times daily)" ~ dis_s4$statistic,
                        measure == "Audio Check-in" ~ dis_a$statistic,
                        measure == "Location" ~ dis_loc$statistic,
                        measure == "SMS Content" ~ dis_sms$statistic,
                        measure == "Logs (SMS/call)" ~ dis_log$statistic),
       d_2 = case_when(measure == "Sleep Monitor" ~ dis_sl$d,
                        measure == "Daily Survey (4 times daily)" ~ dis_s4$d,
                        measure == "Audio Check-in" ~ dis_a$d,
                        measure == "Location" ~ dis_loc$d,
                        measure == "SMS Content" ~ dis_sms$d,
                        measure == "Logs (SMS/call)" ~ dis_log$d),
       sig_2 = case_when(measure == "Sleep Monitor" ~ dis_sl$p.value,
                         measure == "Daily Survey (4 times daily)" ~ dis_s4$p.value,
                         measure == "Audio Check-in" ~ dis_a$p.value,
                         measure == "Location" ~ dis_loc$p.value,
                         measure == "SMS Content" ~ dis_sms$p.value,
                         measure == "Logs (SMS/call)" ~ dis_log$p.value),
         sig_2 = case_when(sig_2 < .001 ~ "< .001***",
                           TRUE ~ as.character(sig_2)))
# 1 year
one_year_tbl <- burden_last %>% 
  select("Sleep Monitor" = sleep_1year,
         "Daily Survey (4 times daily)" = daily_survey_4_1year,
         "Daily Survey (1 time daily)$^a$" = daily_survey_1_1year,
         "Audio Check-in" = audio_checkin_1year,
         "SMS Content" = sms_content_1year,
         "Location" = location_1year,
         "Logs (SMS/call)" = all_logs_1year) %>% 
  gather(key = "measure", value) %>% 
  select(-value) %>% 
  group_by(measure) %>% 
  drop_na() %>% 
  slice(1) %>% 
  mutate(mean_3 = case_when(measure == "Daily Survey (4 times daily)" ~ use_s4$estimate,
                         measure == "Daily Survey (1 time daily)$^a$" ~ use_s1$estimate,
                         measure == "Sleep Monitor" ~ use_sl$estimate,
                         measure == "Audio Check-in" ~ use_a$estimate,
                         measure == "SMS Content" ~ use_sms$estimate,
                         measure == "Location" ~ use_loc$estimate,
                         measure == "Logs (SMS/call)" ~ use_log$estimate),
         SD_3 = case_when(measure == "Daily Survey (4 times daily)" ~ use_s4$sd,
                        measure == "Daily Survey (1 time daily)$^a$" ~ use_s1$sd,
                        measure == "Sleep Monitor" ~ use_s1$sd,
                        measure == "Audio Check-in" ~ use_a$sd,
                        measure == "SMS Content" ~ use_sms$sd,
                        measure == "Location" ~ use_loc$sd,
                        measure == "Logs (SMS/call)" ~ use_log$sd),
         t_3 = case_when(measure == "Daily Survey (4 times daily)" ~ use_s4$statistic,
                       measure == "Daily Survey (1 time daily)$^a$" ~ use_s1$statistic,
                       measure == "Sleep Monitor" ~ use_sl$statistic,
                       measure == "Audio Check-in" ~ use_a$statistic,
                       measure == "SMS Content" ~ use_sms$statistic,
                       measure == "Location" ~ use_loc$statistic,
                       measure == "Logs (SMS/call)" ~ use_log$statistic),
         d_3 = case_when(measure == "Daily Survey (4 times daily)" ~ use_s4$d,
                       measure == "Daily Survey (1 time daily)$^a$" ~ use_s1$d,
                       measure == "Sleep Monitor" ~ use_sl$d,
                       measure == "Audio Check-in" ~ use_a$d,
                       measure == "SMS Content" ~ use_sms$d,
                       measure == "Location" ~ use_loc$d,
                       measure == "Logs (SMS/call)" ~ use_log$d),
         sig_3 = case_when(measure == "Daily Survey (4 times daily)" ~ use_s4$p.value,
                         measure == "Daily Survey (1 time daily)$^a$" ~ use_s1$p.value,
                         measure == "Sleep Monitor" ~ use_sl$p.value,
                         measure == "Audio Check-in" ~ use_a$p.value,
                         measure == "SMS Content" ~ use_sms$p.value,
                         measure == "Location" ~ use_loc$p.value,
                         measure == "Logs (SMS/call)" ~ use_log$p.value),
         sig_3 = case_when(sig_3 < .001 ~ "< .001***",
                           TRUE ~ as.character(sig_3)))

# display and format table
interfere_tbl %>% 
  full_join(dislike_tbl, by = "measure") %>% 
  full_join(one_year_tbl, by = "measure") %>% 
  mutate(measure = factor(measure, levels = c("Audio Check-in", "Daily Survey (4 times daily)", 
                                              "Daily Survey (1 time daily)$^a$", "Sleep Monitor",
                                              "Location", "Logs (SMS/call)", "SMS Content"))) %>% 
  arrange(measure) %>% 
  kbl(col.names = c("Personal Sensing Measure", "<i>M</i>", "<i>SD</i>", "<i>t</i>", "<i>d</i>", "<i>p</i>",
                    "<i>M</i>", "<i>SD</i>", "<i>t</i>", "<i>d</i>", "<i>p</i>",
                   "<i>M</i>", "<i>SD</i>", "<i>t</i>", "<i>d</i>", "<i>p</i>"),
      align = c("l", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c", "c"),
      caption = "<b>Table 4</b><br><br><i>Means, Standard Deviations, t-values, effect sizes, and p-values from One Sample t-Tests of Each Personal Sensing Measure against a Neutral/Ambivalent Acceptability Score of 0</i>",
      digits = 2,
      escape = FALSE) %>% 
  row_spec(row = 0, align = "c") %>% 
  kable_classic(html_font = "Times New Roman") %>% 
  add_header_above(c(" " = 1, "Interference" = 5, "Dislike" = 5, "Willingness to continue" = 5)) %>% 
  pack_rows("Active", 1, 4, bold = FALSE) %>% 
  pack_rows("Passive", 5, 7, bold = FALSE) %>% 
  footnote("Acceptability measures are on a 5-point scale centered around a neutral/ambivalent score of 0 (i.e., undecided) and with 2 being highest on acceptability and -2 being lowest on acceptability. Sample size for all personal sensing measures is 154 except for the sleep monitor which had a sample size of 87.<br>$^a$<i>This measure was hypothetical in that although participants were asked about a one-time daily survey, they were expected to complete the survey four times each day.</i>", escape = FALSE)
```

<br>



