---
output:
  pdf_document:
    includes:
      in_header: !expr here::here("..", "lab_support", "rmd_templates", "latex", "header.tex")
    template: !expr here::here("..", "lab_support", "rmd_templates", "latex", "nih_latex_template.tex")
    keep_tex: no
    number_sections: no
    latex_engine: xelatex
    citation_package: default
header-includes:
  - \usepackage{helvet}
  - \usepackage[T1]{fontenc}
  - \renewcommand\familydefault{\sfdefault}
geometry: margin=.5in
fontsize: 11pt
---

Dear Dr. Buis,

We are pleased to submit a revised version of our manuscript "Acceptability of personal sensing among people with alcohol use disorder: Observational study" (Manuscript No. JMU 41833) for your review at JMIR mHealth and uHealth. Below, we delineate the reviewer’s and action editor’s questions, concerns, and requests regarding our revised submission, and we detail the ways in which we have addressed each item.

Sincerely,

Kendra Wyant, Hannah Moshontz, Stephanie Ward, Gaylen Fronk, & John Curtin

---




# Action Editor's Comments

## AE.1:  Please note that Reviewer O's comments are underneath your previous responses to each of the previously identified concerns. They are noted with hash tags.
We addressed Reviewer O's comments below. To reduce redundancy we removed comments from the previous round of review that have been resolved to Reviewer O's satisfaction.

## AE.2: This paper is still exceptionally long and will likely incur additional copyediting costs if accepted due to the word length.
We are willing to incur the additional copyediting costs if accepted due to word length. 

# Reviewer O Comments:

## RO.2: The title of the larger project suggests that sensors would be used to prevent relapse. Is there a risk that participants have been motivated by clinical benefit even if that was not the intention?
Participants were explicitly instructed at numerous points in the study that the only benefit for participation was financial compensation. They were informed that the personal sensing would not be used to monitor their current risk or to select, deliver, time, or adaptive any interventions to their needs. The Procedure section of the Methods has now been updated and supporting materials (i.e., consent form, recruiting flyer) added to our OSF page to more clearly reflect this.   
-- Thank you for your explanation and for providing the additional information. I do not believe you statement about financial compensation being the only benefit is correct. The first line under benefits in the consent form states: "You will receive additional support to aid you in your efforts to remain abstinent from alcohol" also the alternatives to participation presented are different ways of getting more treatment.

---
We now make clear participants may have experienced some clinical benefit while participating in our study (see paragraph 5 in the Benefits Likely Matter section of Discussion). 



## RO.4: Background provides a good overview of the use of mobile sensors in psychiatry. But it is sometimes unclear when the statements refer to alcohol or substance use and what is more general in mental health.
We have edited the introduction to clearly identify when we are reviewing/citing studies that refer to samples with broader psychiatric disorders vs. narrower alcohol and other substance use disorders.   
-- Thank you for addressing this. I think it could be further improved by more clearly state which areas/types of sensing have been studied for substance use. For example in the following only ref 13 and 15 seem to be regarding substance use?: "More recently, research using personal sensing of raw data streams other than self-report is emerging for mental health broadly, including alcohol and other substance use disorders. This includes methods to sense geolocation [13–15], cellular communications [15–19], sleep [19], and physiology [20,21], as examples." And in the following eight references on different substances and aims are all thrown in together: "For alcohol and other substance use disorders, research is emerging now to used sensed data to predict craving, alcohol, cannabis, or opioid use, and lapses/relapse [13,29–36]"

---
We have added additional substance use references (29-32,35) to the characterization of different personal sensing methods. Additionally, we now break apart the substance use references to be more clear about each study's outcome (i.e., craving, use, lapses/relapse).


## RO.6: What previous research have been made on the different sensing methods for alcohol use disorder? (Bae 2018, Stevenson 2020, Scott 2020…)
We have expanded our review of sensing methods for alcohol and other substance use disorder.  This expanded review includes the papers cited here along with other relevant papers.  See point RB.2 above.    
-- Thank you for adding more recent references. It is still not possible to get a clear picture of the knowledge on different methods for alcohol specifically from your introduction.

---
We have broken up the references to be more clear about which are related to alcohol specifically (29-31,33). See point RO.4 above.  We have not opted to further expand the review of the literature in the introduction as the editor has already noted that our paper is longer than typical for this journal.  The goal of the introduction was simply to provide a framework for the study; this paper is not intended to be a stand-alone review.


## RO.10: What was the reason for the sobriety requirement? Many people with AUD prefer a moderation goal. Would not the sensors work just as well with moderate consumption?
Most future applications of sensing in the AUD/SUD domain target patients in recovery with plans to use sensing to help them monitor for lapses/relapses and/or select and adapt digital interventions to address their momentary needs.  For this reason, we wanted our sample to consist of people who were in recovery rather than simply continuing harmful use.  We used alcohol abstinence as a behavioral indicator of a commitment to recovery. Although, recovery may be possible without complete abstinence, clinicians typically recommend abstinence for patients who present with moderate or more severe AUD (see Eddie et al., 2022). We now provide this rationale for the abstinence inclusion criterion as a footnote.    
-- Thank you for explaining. To be clear, I did not suggest participants with continued harmfull use. Even if there are reasons to always suggest abstinence as a treatment goal, many patients prefer and may only seek treatment to reach moderation. Eddie et al., 2022 also show that moderation may be a safe, valid pathway to recovery. My question was if your methods would work with this broader population or if there are technical- or design reasons for requiring a goal of abstinence.  

---
Thank you for clarifying your question. There are no technical reasons preventing our methods from being applied to other substance use populations (e.g., people with a goal of moderation). So long as someone has a clear recovery goal (number of drinks, number of drinking days, etc.), we anticipate personal sensing could be used to aid in their recovery (see Bae et al., 2017 and Walters et al., 2021 for examples of predicting current and imminent drinking episodes in people without a goal of abstinence). We have added this observation about the potential to apply these methods to non-abstinence seeking individuals in the Limitations and Future Direction section of our discussion (see paragraph 5).  




## RO.19: Have this high sampling density been used in substance use before? Would it be used clinically and if so for what reasons?
As noted earlier (see point RO.9), we now provide more detail about the parent project including the rationale for the high sampling density of many sensed raw data streams.  The aims of that project were to develop a temporally precise (up to one hour precision) machine learning algorithm to predict future lapses back to alcohol use.  Such high temporal resolution is innovative but also very important for the use of "just-in-time" interventions that are designed to be delivered at moments of greatest need.  
-- Ok. I am still interested in getting more information about if this sampling density have been used before and if when in recovery and for how long time-periods this type of just-in-time interventions would be best suited.  

---
We briefly touch on this issue in our introduction (see paragraphs 3-4 of the Acceptability of Personal Sensing section):  
"Participants display moderate or better adherence with respect to response rates even with relatively high sampling density (e.g., 6 -- 9 daily assessments) [45,50,51]. However, these studies generally assessed participants' perceptions and adherence over short monitoring periods (i.e., 2 -- 6 weeks).  Less is known about the use of EMA over longer duration monitoring periods (e.g., months) as would be necessary for clinical applications."   

"Existing research also raises some concern about perceptions and adherence to EMA protocols in patients with alcohol and other substance use disorders relative to other groups.  Specifically, a recent meta-analysis confirmed decreased adherence to EMA protocols in patients with substance use disorder diagnoses vs. recreational substance users [52]."  

To be clear these studies suggest high sampling density is sustainable for short periods of time in research applications. It is unclear from the literature how long one might adhere to a more intense EMA protocol. Our study attempts to shed some light on this issue by using high density sampling (4 x's per day) for 12 weeks. We also obtain open-ended feedback on the method. Although the implementation of personal sensing into just-in-time interventions is outside the scope of this project, we do inquire about their willingness to maintain a 4 x daily EMA protocol for one year to help their recovery and a 1 x daily EMA protocol for one year to help their recovery.



## RO.20: It is not clinically reasonable to remind people with 2-3 months abstinence about their alcohol use problems 4 times a day. This could have side effects on emotional state or drinking. Have you considered this?
The goals of most contemporary treatments (e.g., Cognitive-Behavioral Relapse Prevention, Mindfulness Based Relapse prevention) are to train and encourage patients to carefully monitor themselves and their environments for risks to their recovery.  Alcohol and other substance use disorders are chronic relapsing disorders and patients must learn to sustain such monitoring long-term, if not for the rest of their lives.  Careful, frequent monitoring is very important during early recovery (the period studied in our sample).  Of course, frequent and/or long-term monitoring is very difficult to achieve.  That is why we (and other research teams) are pursuing the use of sensing combined with machine  learning prediction algorithms to support such monitoring automatically.  We now highlight these goals of the parent project (see point RO.9).  Our use of both active methods (that explicitly ask people about experiences that might affect their recovery via EMA) and passive methods that can potentially assess these same risks but without burden or explicit attention was intentional to allow us to compare the potential acceptability (this study), burden (this study), and predictive power (subsequent aims of parent project).    
-- Thank you. I have worked for many years both clinically and in research with CBT-methods for AUD. I agree with you that careful, frequent monitoring is important during early treatment. But there may be considerable side-effects of forcing people to think about their previous alcohol use many times each day. I do not agree with you that "patients must learn to sustain such monitoring long-term, if not for the rest of their lives". That is very different from being aware of increased risks for future problems. For many patients it is both a stated goal and a sign of progress, when they after long abstinence, are able to go periods without thinking about alcohol. Effective treatment interventions always have the risk of having side-effects for some users. I encourage you to consider this in your continued work and allow users to report any negative experiences.   

---
Thank you for the feedback. We agree and constrain our generalizations of acceptability to people early in recovery (see Paragraph 2 of Limitations and Future Directions section of the Discussion).  

"This 3-month period also constrains our conclusions of acceptability to people early in recovery. It is possible that acceptability ratings will vary depending on where someone is in their recovery. This may also be amplified when we consider potential benefits. For example, someone who has achieved long-term stability in their recovery could find the costs of personal sensing (e.g., data sharing, high effort demands) do not outweigh the benefits (e.g., daily reflection on sobriety, potential for increased lapse risk awareness). It is important for future studies to extend study length and incorporate other facets of acceptability (e.g., benefits) to account for these possible effects."

We will keep these issues salient as we continue this work and future studies will probe more carefully for negative experiences associated with frequent sampling. 



## RO.23: There are several indications that the individuals in this sample are different from other individuals with alcohol use disorder in regard to their perception of mobile sensing. The large proportion of people agreeing to participate in research probably depend a lot on where and with what message the participants were recruited and what information they got about the project. This should be described in much more detail for others to be able to get the same results and to be able to judge what, if anything, the high proportion of people agreeing say about personal sensing.
We have provided additional details about the recruiting, screening, and consenting process.  This includes additional information in the Method in the Procedure section and the Compensation section.  We also clearly enumerate all study exclusion and inclusion criteria (see Exclusion and Inclusion Criteria in the Method).  In addition, we also now share the recruitment flyer and the consent form on the OSF study page to provide full transparency about recruitment and consent (see point RO.8 for more detail).   
-- Ok, thank you for providing this additional information. The recruitment flyer probably have attracted people interested in mobile health technology, rather than all people in recovery. This is not mentioned under limitations.   

---
We now mention this as a limitation in the Limitations and Future Directions section of the Discussion (see paragraph 5).


## RO.29: The authors argue that reimbursing participant is common in many studies and even in clinical settings. Even if this is true it is a big limitation than should be clear from the abstract. The way the sample was recruited and informed about the project should be more clearly discussed under benefits.
We may not fully understand this issue.  To be clear, it is almost universal in research studies in psychology to provide participants with some form of compensation (monetary or otherwise) for their participation in the study.  Of course, the level of compensation has to be consistent with the tasks/effort expected from research participants and not so high as to be considered coercive.  Such issues are evaluated explicitly when studies are evaluated by IRBs.  We have clarified participant compensation for this study (see Compensation section in the Method) so that this information is clearly available to readers.  We have also edited the abstract to make clear that participants were compensated to engaged in the personal sensing methods.   

In the discussion, we acknowledge that it is possible for clinical interventions/treatments to include compensation/payments to patients.  In fact, contingency management (e.g., https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3083448/) is a treatment that explicitly includes compensation to patients to encourage them to engage in healthy behaviors (e.g., not using drugs) or adhere to other beneficial treatments. Given this, we believe that it may be possible (though it may not be necessary) within such a framework to compensate patients to provide some personal sensing data if those data can be used to improve their health as part of a monitoring or adaptive intervention system.  We have attempted to clarify this discussion further in the revised manuscript.     
-- Thank you for the additional information added. As stated, I agree that reimbursement is common, but the way you used reimbursements may have effected your results and you need to acknowledge this more clearly in your discussion. It also makes this less of a clinically relevant study. Even if treatment methods like CM are supported, they are not possible to use everywhere.   


---
We acknowledge that the financial incentive may have influenced our findings in the Benefits Likely Matter section of the Discussion.     

"However, the incentives to provide access to passively sensed geolocation and cellular communications in our study may have contributed to the acceptance of these methods and the success we had collecting those sensitive data from participants. This may be particularly true given the relatively low socioeconomic status of many of our participants. For example, the median personal income for our participants was $34,233, with 12.3% (19/154) of individuals reporting current unemployment and 25.3% (39/154) reporting an annual income below the 2022 federal poverty level."    

We now also make more clear the importance of comparing different types of benefits in clinical settings in this same section.    

"Future research should evaluate the acceptability of personal sensing in contexts where its use directly benefits those providing the sensed data.  In these contexts, benefits (e.g., financial, clinical) can also be explicitly measured.  It may even be possible to manipulate the benefits from personal sensing across participants to evaluate their contribution to acceptability more rigorously."

And we now more clearly bring attention to the need for further testing in applied settings in our Limitations and Future Directions section of the Discussion.    

"Finally, while our results suggest clinical samples of people with alcohol use disorder may find these personal sensing methods acceptable, more research is needed to test the acceptability of these methods in future applied clinical settings, where issues of costs, benefits, and trust may differ meaningfully in complicated ways from the research context. Also, it must be acknowledged that individuals in our study agreed to participate in a research study on mobile health and were financially compensated for their time. It is unclear how these individuals and the research setting may differ from those seeking to use these methods in future clinical settings where costs, benefits and trust may all weigh differently on their decisions to engage with the sensing system."

## RO.32: Its contradictory to state that the sensing was acceptable “without explicit clinical benefits to the participants” and at the same time that they can be “used for clinical applications”. The study does not appear to be designed to test clinical application, but recruited a population that seem clinical, with ongoing substance use among many participants.
We now make clear in the method that participants did not receive any explicit clinical benefits from the personal sensing conducted as part of this study.   They did not receive any feedback on the sensed data.  The sensed data were also not used to provide or adapt any interventions for these participants.  As such, personal sensing did not provide them with any clinical benefits in this study.   Our hope is that we can use data collected via personal sensing to develop machine learning algorithms that can be used in FUTURE clinical applications of these methods to both help people monitor their recovery and/or deliver or adapt clinical interventions that are provided to them.   This is a FUTURE possible application.  These algorithms do not yet exist (and in fact, one of the aims of the parent project is to develop such algorithms for future use based on the data collected here).    
-- As stated earlier I do not agree that participants did not expect any clinical benefit with the current design and information given to participants. I any case, I do not think that your design and findings support your general conclusion about acceptability of the methods. The clarification made here in caps, that these methods could be developed for future clinical applications should be better reflected in your conclusions. That people accept to provide you data to use for development of a future intervention, when getting reimbursed, do not mean that they will accept them as a clinical intervention. Some factors in your study, like the population targeted and the information given to them, indicate that they would accept it clinically. There is interesting things to be learned about how personal sensing can be more or less acceptable to patients from your results.    

---
We now clarify that these methods may be developed for future clinical applications after additional research is conducted. We also now emphasize that individuals in our study were being financially compensated and as a result may perceive the acceptability of our methods differently than those in future clinical setting (see paragraph 5 of Limitations and Future Directions section in the Discussion).