---
format: 
  pdf:
    include-in-header:
      - text: \raggedright
      - file: ../includes/h_headers.tex
geometry: margin=.5in
mainfont: ArialMT
sansfont: ArialMT
fontsize: 11pt
bibliography: ./grant_optimize.bib
csl: https://raw.githubusercontent.com/jjcurtin/lab_support/main/rmd_templates/csl/national-library-of-medicine-grant-proposals.csl
---   

# C.  Approach

## C1. Participants

### C1.1. Eligibility. 
416 participants (half female; age 18 years or older) who meet criteria for Alcohol Use Disorder with at least moderate severity (>= 4 DSM-5 criteria assessed via module E of the Structured Clinical Interview for DSM-5[@firstStructuredClinicalInterview])<!--KW: and have a goal of abstinence--> will be recruited nationally via social media and other digital advertising.  They must also be abstinent from alcohol for at least one month and no longer than six months at study intake. <!--KW: Noticed change from RISK abstinence length (1-8 weeks). I think first 6 months of recovery seems to be good length for "early recovery" but wonder why they need 4 weeks abstinence instead of 1 week.--> Participants with medical or psychiatric co-morbidities will not be excluded unless these co-morbidities preclude their use of a smartphone or A-CHESS. Participants must be able to read in English. Participants must have a smartphone and cellular plan that supports A-CHESS use (A-CHESS works with contemporary smartphones using either Apple iOS or Android operating systems). Participant eligibility is assessed during a screening and intake session that is conducted by study staff by video or phone call (per participant preference).  

### C1.2. Measures of Participant Characteristics

Participant characteristics are assessed at the screening/intake session by a Qualtrics survey that is optimized for presentation on both mobile devices and computers. This survey includes measures of demographics (sex, race, ethnicity, income, education level), alcohol use and history (e.g., age first use; years regular use, # quit attempts; previous treatment received), lifetime substance use (World Health Organization's Alcohol, Smoking and Substance Involvement Screening Test[@whoassistworkinggroupAlcoholSmokingSubstance2002]), psychiatric symptoms (PHQ-9[@kroenkePHQ9ValidityBrief2001], GAD-7[@spitzerBriefMeasureAssessing2006]), and health (PROMIS-10[@cellaPatientReportedOutcomesMeasurement2010], which yields global physical and mental health subscales).  These baseline measures will be used both to characterize the participants and as potential covariates in the optimization analyses (<!--UPDATE: see section 4.3.2.1 in Statistical Design and Power-->)

## C2. A-CHESS Digital Therapeutic

During the screening/intake session, participants are guided to install the A-CHESS digital therapeutic.  Participants receive training in the use of A-CHESS by study staff and the participant is required to demonstrate understanding of its basic use (e.g., how to read messages; use of the discussion group; how to complete EMA surveys). Participants are also directed to a website with a robust and comprehensive online orientation and training system, including online training modules and video tutorials. The training website explains the A-CHESS modules how they can be used to help their recovery.

In addition to providing support for relapse prevention, A-CHESS will be used for personal sensing of geolocation (using smartphone location services), A-CHESS module use, and EMA.  Participants are also instructed on how to temporarily disable location services if deemed necessary. At the same time, they are reminded about the confidential nature of their data, the confidentiality protections, and the compensation bonuses for achieving targets with respect to missing data (see section 2.5.2 in Recruitment and Retention).

### C2.1. Why A-CHESS? 
It should be noted that there are currently two other digital therapeutic systems (CBT4CBT[@carrollComputerassistedDeliveryCognitivebehavioral2008a; @carrollEmpiricalIdentificationClinically2014; @carrollComputerAssistedDeliveryCognitiveBehavioral2014] and the Therapeutic Education System[@blackComputerDeliveredInterventionsReducing2016; @campbellInternetdeliveredTreatmentSubstance2014]) that offer recovery support for alcohol and other substance use disorders and have sufficient empirical evidence of their effectiveness[@campbellFirstWaveScalable2023].  We believe our use of A-CHESS vs. these other digital therapeutics in this application is justified for the following reasons. First, for practical reasons, A-CHESS has been developed and studied extensively within our Center.  As such, we control the code and can easily modify code to incorporate our machine learning prediction model and the message components we propose to study in this application.  Similarly, we have extensive support materials (e.g., videos, web documentation) that can be used to instruct participants in the use of the DTx app.   Second, the Therapeutic Education System has focused primarily on increasing retention in treatment (e.g, medications for opioid use disorder) rather than relapse prevention.  This is consistent with its primary focus on opioid use disorder.  Our lapse risk prediction model is best suited for interventions designed to prevent lapses and relapse rather than promote treatment retention.  Third, CBT4CBT has been primarily implemented as a web-based intervention.  As such, it is less well-suited for either personal sensing or machine learning model guided adaptive use.  

However, it is important to note that the aims of this grant are to a large degree independent of the specific digital therapeutic used.  The lapse prediction model itself and the message components that we manipulate to increase the likelihood that participants follow the model's recommendations could easily be incorporated into any digital therapeutic for alcohol use disorder that sensed EMA and geolocation and included modules motivated by the Relapse Prevention model.  As such, conclusions about the optimal message components to increase engagement are not limited to the A-CHESS digital therapeutic but can instead guide development of machine learning model based recommendations in any digital therapeutic for alcohol and other substance use disorders available now or in the future.


## C3. Personal Sensing in A-CHESS

### C3.1. Sensing with Ecological Momentary Assessments (EMAs).

Participants will complete one EMA each day, using built in survey features in A-CHESS. These assessments are brief (less than 1 minute to complete) and interactive via the smartphone touchscreen. Participants set the optimal time during the day for these assessments at screening/intake. They receive a push notification when the assessment is due and a second push notification reminder to complete the assessment if it has not been completed within an hour.  Participants report on their current mood (i.e., affective valence and arousal), their peak alcohol craving since their last assessment, and the occurrence and intensity of any positive events and any stressors/hassles since their last assessment. They also report how likely they are to encounter risky situations (people, places, or things) and stressful events in the next week and how confident they are about abstaining from alcohol use in the next week. They conclude each assessment <!--KW: sometimes this was only question participants completed on EMA. I wonder if moving it to the end would mean participants would wait longer to report drinking, increasing probability of recall bias/inaccurate reporting--> by reporting any alcohol use that they have not yet reported, the time of the start of that use, the duration of the drinking episode, and the number of drinks consumed.  Monetary compensation is provided for completing each EMA and for achieving compliance thresholds (see section 2.5.2 in Recruitment and Retention).  Curtin has used these EMA items and compensation strategy in two previously NIH funded projects.  Published research[@wyant_acceptability_2023] from R01-AA024391 documents that participants with alcohol use disorder completed 81% of the 4x daily EMAs they received and 94% of the participants completed at least 1 EMA daily (as proposed in this project) every day for up to three months.  In R01-DA047315 (data collection ongoing), participants with Opioid Use Disorder completed 82% of the 1x daily EMAs they received for up to one year.

### C3.2. Sensing of Contexualized Geolocation.

Participants’ current location will be continuously tracked by A-CHESS using location services on the smartphone. We increase the predictive signal of location information by gathering contextual information about the locations that participants visit frequently (>= 2x per month).  Specifically, for frequent locations, participants report the location type (e.g., home of friend, bar, restaurant, workplace, AA meeting location), if alcohol is typically present at that location, if they have drank there previously, their typical emotional experience at that location (pleasant, unpleasant, mixed, neutral), and the perceived risk to their recovery associated with that location.  This contextual information can be gathered quickly by appending these additional questions about a newly detected frequent location to their next EMA.  We query at most one new frequent place in any daily EMA.  These A-CHESS capabilities for geolocation tracking and the collection of contextual information about frequent locations were developed as part of a previously funded NIAAA project (R01-AA024391) and are in use currently in our NIDA funded project (R01-DA047315).  We have also published details on this method for collecting geolocation context [@moshontzProspectivePredictionLapses2021].  Across 154 participants with alcohol use disorder, 100% opted-in to provide us with location information[@wyant_acceptability_2023],<!--KW: do we have info on how many RISK2 opted in, like we report for EMA?--> demonstrating that participants are willing to provide us with this sensitive information given the protections we provide.  In addition, contextual information can be collected with relatively low burden as most individuals have only a small number of locations that they visit frequently (i.e., ~31 places for participants with alcohol use disorder in R01-AA024391).  


## C4 Smart A-CHESS Machine Learning Lapse Risk Prediction Model

### C4.1 Predicting Future Lapse Probability.

For the research in this application, we are using a version of A-CHESS (we call it Smart A-CHESS) that has been enhanced by the addition of a machine learning model (described in section A10) that predicts the probability of a lapse back to alcohol use in the next day.  This XGBoost model was trained using approximately 300,000 labeled observations from 151 participants with moderate to severe alcohol use disorder[<!--insert refs-->].  This model uses features engineered from both sensed geolocation and EMA collected by A-CHESS (see section C3).  These features tap into key constructs from the Relapse Prevention model such as craving, affect, stressors, lifestyle imbalances, high risk situations, self-efficacy/confidence, and abstinence violation effects.  The model's predictions have high combined sensitivity and specificity as indicated by its area under the receiver operating characteristic curve of 0.91  <!--check this--><!--KW: confirmed day model auROC from EMA is .91. Do we need to run models with GPS and EMA together?-->.  This machine learning prediction model can be used to provide both the probability of a lapse back to alcohol use in the next 24 hours and the change in that lapse probability (e.g., is it increasing, decreasing or stable) over the past two weeks.  Model predictions can be updated for each participant every hour.  

### C4.2 Identifying Personally Risk-Relevant Interventions and Other Supports.

We also apply techniques from the rapidly advancing field of interpretable machine learning[@molnarInterpretableMachineLearning2022] to identify which model features are making the largest/most important contributions to the current predicted lapse probability for any participant at any time.  Feature importance is quantified (in log-odds units) using local SHAP (SHapley Additive exPlanations) values[@molnarInterpretableMachineLearning2022; @lundbergUnifiedApproachInterpreting2017] associated with each model prediction.  Important features are features that substantially increase or decrease the predicted probability of lapse for that participant at that time from the aggregate (across all participants and times in the original training data) lapse probability.  We consider features that increase or decrease the log-odds of a lapse by > |.1| clinically important for binary classification models[@molnarInterpretableMachineLearning2022].  By extracting local (i.e., for a specific, single  prediction) feature importance, we can use the machine learning model to determine not only the probability of lapse and its change over time, but also information about why that lapse is likely or unlikely to happen.  

<!--KW: Maybe this is where we need to more explicitly define "risk-relevant DTx engagement"-->
And as described earlier, the prediction model's features have been anchored within the constructs of the Relapse Prevention model, which allows us to use the Relapse Prevention model to identify interventions and other supports in A-CHESS that are personally relevant to that participant at that moment in time to address their risk<!--KW: (e.g., to promote risk-relevant DTx engagement)-->.  Following Fisher et al.[@fisherDynamicModelPsychological2015; @fisherOpenTrialPersonalized2019; @fernandezDevelopmentInitialImplementation2017], combinations of lapse probability (categorized into low, moderate, or high risk) and important features are mapped to specific A-CHESS modules using a mapping matrix based on clinical expertise guided by the Relapse Prevention model. Combinations of lapse probability and important features (i.e., cells of the mapping matrix) often map to more than one appropriate module. For example, if craving is important and lapse probability is low, multiple useful urge management modules exist within A-CHESS (e.g., guided urge surfing, distracting games and activities).  Thus, this procedure allows us to use the lapse prediction model to identify the set of interventions and supports in A-CHESS that are most personally relevant to the participant at that moment in time given their recent sensed experiences, current lapse probability, and important risk features.


## C5 Smart A-CHESS Engagement Messages

Smart A-CHESS sends daily **engagement messages** to users.  These engagement messages are designed to increase participant engagement with its interventions and other support modules.  These engagement messages are sent by direct message within Smart A-CHESS to the participant's inbox each day.  Messages will be sent overnight <!--KW: quietly? What if someone likes to keep their phone sound on while sleeping? Maybe have the message available overnight but the notification sent at their usual wakeup time.--> (based on the participant's typical sleep schedule) to allow them to be generally available by the start of the new day when they wake.  Smart A-CHESS supports push notifications for messages.  Default settings display notifications in the notification center, on the lock screen, and by modifying the A-CHESS app icon.  A message reminder is sent 6 and 12 hours after initial receipt of the message if it has not been read (and message status as read/unread is sensed, time-stamped, and available for secondary analyses).  Participants are able to configure these push notifications and reminders to suit their personal preferences.

A simple statement that encourages the participant to engage with A-CHESS that day forms the core of each engagement message.   This core engagement statement also includes language to either convey empathy or the feasibility of using A-CHESS modules that day.  The emphatic language is generated using the Empathic Communication Coding System, that is based on principles of comforting and politeness strategies [@burlesonConsistenciesTheoreticalNaive1985; @bylundEmpathicCommunicationGender2002] and has been related to positive health outcomes in medical advice settings[@parkinGreaterProfessionalEmpathy2014]. Co-I Van Swol is using this system in ongoing research to assess empathy in health chatbots dispensing exercise advice.  The feasibility language is generated using an established advice feasibility scale [@macgeorgeUnderstandingAdviceSupportive2004].  Research by Co-I Van Swol demonstrates that when advice feasibility was increased this way, it was more likely to be used by decision-makers, particularly if they are already interested and committed to making changes to their behavior [@chungPromotingReforestationLandowners2020; @sarmientoUsesStagesChange2022].  
<!--KW: including these components in every message prevents us evaluating whether these components are actually needed to optimize the message. What if a simple reminder statement is just as effective? This would be less complicated and more efficient. It also is more in line with what we would expect standard non-varying reminders to look like in current dtx's but would need to check this. Also additional manipulations may not affect power too much?-->

<!--KW: just noticing 6 uses of forms of vary in this paragraph. Could substitute some for synonyms.-->
These statements are drawn from a large pool of statements that vary with respect to the empathetic or feasibility language included to allow for variety in the messages.  This variety, combined with the variety and personalization of the message components described below, follows best practice recommendations to provide variety and novelty in messages by varying content, form, drawing from message banks that contain equivalent statements versus verbatim repetition, or matching messages to individuals’ personal contexts [<!--refs 22–24-->].

### C5.1 Manipulation of Engagment Message Components.
In addition to the core engagement statement described above, we append additional, personalized information derived from the lapse prediction model that is intended to increase risk-relevant<!--KW: we should maybe define what we mean by this earlier. Also consider emphasizing here as well as later when describing clinical outcomes.--> DTx engagement with A-CHESS that is expected to improve clinical outcomes.   This information from the lapse prediction model is parsed independently across **four message components** that can each be added to the core engagement statement to complete the full engagement message.  The four message components are  1) lapse probability, 2) lapse probability change, 3) an important lapse feature, and 4) a risk-relevant module recommendation.  Specific detail about each of these components is provided below.  

The inclusion of each of these four message components is manipulated within a four-way factorial between-subjects design that serves as the independent variables in the analyses targeting Aims 1-2.  Each component is operationalized to be binary (include or exclude) so that each is either included or excluded from the full Engagement Message delivered to the participant.  
<!--Add statements about the use of this design for MOST.  The power of this design when binary factors. -->
<!-- forms the IVS for Aims 1-2-->
The four message components are operationalized as follows:

### 1. Lapse probability (include or exclude in engagement message): 
If included, the engagement message will contain categorical information about the participant's lapse probability in the next 24 hours.  Lapse probability will be provided using a three-level categorization of "low-risk" (probability <= .05), "moderate-risk" (.05 < probability <= .20), or "high-risk" (probability > .20).  These probabilities were determined both based on clinician input and distributional information from the sample of 151 participants with alcohol use disorder where we developed our algorithms.  With respect to the latter, these probabilities represent approximately the $10^{th}$ and $60^{th}$ percentiles in the overall distribution of the ~300,000 observed probabilities.  The decision to convey lapse probability categorically (rather than numerically) follows current best practice recommendations to avoid complex numerical probability statements, especially for those with low numeracy, and provide the minimal information needed to assess magnitude of risk, weigh options, and act [<!-- refs 10-14-->].  It also follows the feedback format from an existing app about risk associated with blood alcohol concentration levels [<!--ref 3-->].

<!--KW: these decisions sound reasonable and well-justified!-->

### 2. Lapse probability change (include or exclude in engagement message): 
If included, the engagement message will contain categorical information about changes in the probability of a lapse over the past two weeks.  Lapse probability change will be reported using a three-level categorization of "decreasing risk" (lapse probability decreases by >= .05 over two weeks), "increasing risk" (probability increases by >= .05 over two weeks), or "stable risk" (probability changes by < .05 over two weeks).  Lapse probability change is quantified by regressing the participant's lapse probabilities over the past two weeks as a linear function of time (days).  Expected lapse probability change over 14 days is then obtained from this linear model.  The decision to evaluate lapse probability change, in addition to absolute level of lapse probability provided by the first component, follows recommendations that trajectory information can make subtle changes in risk level more apparent,  can relieve cognitive load associated with monitoring, and can provide incremental value beyond absolute risk levels[<!--ref 2-->].  This component is modeled on a human-centered decision support system to alert clinicians about worsening quality of life conditions in ALS patient care-giving[<!-- ref 15-->] The decision to convey this information categorically follows the same best practice recommendations as for lapse probability [<!--refs 3, 10-14-->]. <!--KW: I think the second to last sentence is not needed. Or perhaps make connection a little more clear since it is such a deviation from mental health/aud (e.g., something about chronicity). Also, it leaves me wondering why then we say we convey the info categorically following best practice for lapse probability. Does the ALS monitoring system not use categorical messaging?-->

### 3. Important feature (include or exclude in engagement message): 
If included, the engagement message will contain a description of one important feature <!--KW: feature category?--> contributing to the participant's predicted lapse probability at that time.  The direction of the feature's effect on lapse probability (i.e, increase or decrease lapse risk) will be included.  The feature will be selected from among the set of important features at that time as defined by the features' SHAP values. Among this set of important features, features will be ranked/sorted by how often they have been included in recent engagement messages and then the magnitude of their SHAP value.  This will prioritize providing the participant with information about new but also important risk features.  We include this message component because providing risk feature information may help participants both identify which issues to target for change, and select appropriate A-CHESS intervention and support modules matched to these issues [<!--ref 17-->].  Emerging best practices from interpretable machine learning suggest this information may make the machine learning model less of a "black box", which may build trust, or allow individuals to engage more thoughtfully (e.g., questioning false positives, scrutinizing model behavior)[<!-- refs 18-20-->].


### 4. Risk-Relevant Module Recommendation (include or exclude in engagement message): 
If included, the engagement message will contain a suggestion to consider using a specific A-CHESS module that has been identified by the lapse prediction model as personally risk-relevant given their lapse probability and important features (see section C4.2).  If the participant is in a condition where they will also be provided with important feature information (component 3 above), the risk-relevant module recommendation will be selected to be consistent with the feature information they are provided. <!--KW: Could be more clear. e.g., A risk-relevant feature that the module aims to target will be selected as defined in section C4.3. This ensures that the module recommendation will always be consistent with the feature information, when provided.-->  As with feature information above, when multiple risk-relevant modules are available and appropriate given the lapse risk prediction model output, modules will be selected to prioritize new modules that have not yet been recommended and de-prioritize modules that have been previously recommended by not used by the participant.  We include this message component following best practice suggestions to pair risk information with specific action recommendations to address the risk [<!-- ref 9-->]. This component follows directly from the guiding thesis of our research that improved clinical outcomes will follow increases in adaptive, personally-relevant engagement rather then simply more engagement<!--KW: maybe reword as "unguided general engagement" to make difference more clear.--> with a digital therapeutic. This component also follows recent examples of digital therapeutics that used machine learning prediction models 1) to generate personalized nutrition goal suggestions for individuals with type 2 diabetes [<!--ref 21-->] and 2) to deliver micro-interventions to prevent diet lapses based on diet lapse risk and risk features [<!--ref 1-->]. <!--KW:these references in the last sentence also feel just thrown in. Without reading the citations, it is unclear the direct relationship or what is meant by generating personalized nutrition goals (i.e., daily goals? are they just goals or are there actionable steps to take to meet these goals?). Also what kind of micro-interventions? Are these similar to what we would be recommending people with AUD do?-->

## C6.  Study Outcomes

We will evaluate the effects of these four message components on proximal measures of DTx engagement (Aim 1) and more distal measures of clinical outcomes (Aim 2).  In Aim 3, we test and carefully characterize predicted daily relationships between DTx engagement and clinical outcomes.  

### C6.1 DTx Engagement Outcomes (for Aim 1)
Our primary optimization outcome for this study is **Days of risk-relevant DTx module use**.  We will use this outcome measure to select the message components to be included in final optimized version of Smart A-CHESS that is delivered as a product of this grant. <!--WHY optimize on this measure--> As noted earlier, these same optimal message components could also be included in other DTx apps that include machine learning models to predict lapse probability in the future.   

Days of risk-relevant DTx module use is passively sensed by A-CHESS with total days quantified separately across the first and second three-month periods of the study.  As described earlier, risk-relevant A-CHESS modules are identified for each participant each day based on the important model features (use local SHAP values from the model) that contribute to that individual's specific lapse probability that day.  On many days, more than one A-CHESS module may be risk-relevant for an individual and use of any of those personally risk-relevant modules will count as risk-relevant DTx use for that day.  The start for each 24-hour "day" coincides with the arrival of each participant's daily engagement message (and ends with the arrival of the next day's message)

We will also measure **Days of other DTx module use**, which includes any use of other intervention, support, or psycho-educational modules in A-CHESS that are not linked to their personalized risk features for that day.  This will not include use of A-CHESS for EMAs (which is required of all participants) or other features (e.g., communications with study staff through the app) that are not designed to be clinically beneficial.  This outcome is also sensed passively by A-CHESS and will be scored for the first and second three-month periods of the study.  This outcome can be used in secondary analyses that contrast the effects of our message components on engagement with the specific modules that are deemed most clinically beneficial that day vs. simply general increases in A-CHESS engagement more broadly.  A driving theme of this research, guided by precision mental health goals, is that better outcomes will be associated with personalized, risk-relevant engagement rather than simply more engagement with a DTx (see also Aim 3, which specifically tests this hypothesis)    

For both of these outcomes, we chose to measure days of use rather than other metrics (e.g., duration of module use) because the time required to effectively engage with a module varies widely across modules. More time with a module does not necessarily mean it was used more effectively. Nonetheless, duration of A-CHESS use overall and duration of module use is also passively sensed by A-CHESS and available for secondary analyses.

### C6.2.  Primary Clinical Outcomes (for Aim 2).

We will evaluate the effects of the four message components on two clinical outcomes recommended by the Food and Drug Administration (FDA)[@foodanddrugadministrationAlcoholismDevelopingDrugs2015] for the evaluation of interventions for alcohol use disorder: **Number of drinking days** and **Number of heavy drinking days**. These two outcomes are quantified for the third and sixth month during the study period.  Information about participant alcohol use is obtained from two sources.  First, participants report episodes of alcohol use in the daily EMAs as described earlier.  Second, study staff conduct a 30-day Alcohol Timeline Follow-back (TLFB) procedure[<!--insert ref-->] at the three and six month study visits.  The TLFB procedure is a calendar-assisted retrospective reconstruction of how many standard alcoholic drinks were consumed by the participant each day in the assessment period. This procedure is further enhanced by adding previously reported drinking episodes (dates, times, and number of drinks) from the EMAs to the calendar used with the participant.  This provides an opportunity to validate those previous reports and collect any additional drinking episodes that may have been missed by the EMAs.  Number of drinking days is defined as the number of days that any alcohol is consumed during the relevant 30 day period.  Number of heavy drinking days is defined as the number of days that >3 (women) or >4 (men) standard drinks are consumed during the relevant 30-day period.  We chose to measure these two outcomes at three and six months as our primary outcomes for Aim 2 for two reasons.  First, the FDA specifically recommends the measurement of these two constructs (i.e., both non-abstinence and heavy drinking) using the TLFB procedure for at least six months in studies that will evaluate AUD treatments.  Second, the FDA and others have noted that these measures are stable indicators of longer-term outcomes by about three months[@witkiewitzTemporalStabilityHeavy2017]. We choose to limit the study duration and measurement of outcomes to six months to be cost efficient.  This is justified because 1) it conforms to FDA guidance to measure outcomes up to six months[@foodanddrugadministrationAlcoholismDevelopingDrugs2015], 2) available evidence indicates these measures are stable indicators of longer-term outcomes by as early as three months [@witkiewitzTemporalStabilityHeavy2017; @foodanddrugadministrationAlcoholismDevelopingDrugs2015], and 3) it is consistent with the MOST framework that recommends cost efficient procedures that support repeated, rapid, iterative development and evaluation.  We limit our measurement of these two outcomes to the 30-day period preceding the three and six month visits to allow us to collect the most reliable measure of drinking by combining data gathered from both EMA and TLFB.

We will also collect measures of psychiatric symptoms (anxiety using GAD-77[@spitzerBriefMeasureAssessing2006], depression using PHQ-9[@kroenkePHQ9ValidityBrief2001]) and global physical and mental health (using PROMIS-10[@cellaPatientReportedOutcomesMeasurement2010]).  Baseline measures of these constructs are collected as part of our characterization of the sample (see section C1-2).  We collect these measures again at three and six months to explore broader potential benefits beyond clinical measures associated with AUD that may be associated with the use of Smart A-CHESS.


### C6.3 Daily DTx Engagment and Clnical Outcomes (for Aim 3)

For Aim 3, we examine the relationship between DTx engagement and clinical outcomes with high temporal specificity (i.e., daily measurement).  This will allow us to determine 1) if increased DTx engagement is associated with improved clinical outcomes, 2) if this relationship is stronger for risk-relevant DTx engagement than for other DTx engagement, and 3) if this relationship is stronger when lapse probability is higher.  These day-level analyses will use day-level measurement of the above described engagement and clinical outcomes.  Specifically, we use passively sensed data to score binary measures (yes or no) to indicate if the participant: 1) engaged with a risk-relevant DTx module, 2) engaged with other DTx modules, 3) drank any alcohol,<!--KW:these last 2 are not passively sensed. "we use EMA and passively sensed DTx data to score..."--> and 4) drank >3/4 (for women/men) drinks for each day (defined as above by the timing of engagement messages) across the full six month study period. Daily lapse probability for each participant is provided by the lapse risk prediction model.  These measures are analyzed within generalized multi-level models as described in <!--UPDATE: section 4.3.2.1 in Statistical Design and Power-->


## C7  Preliminary Data

Throughout the Significance and Approach sections, we have described the substantial preliminary data we have to justify the feasibility, innovation, and potential impact associated with the pursuit of our specific aims.  

<!--Summarize here and add anything not included elsewhere-->


## C8 Design Considerations
Throughout the Approach section, we endeavored to identify key design decisions and associated justifications in the relevant sections that described each design features.   ....


<!--Summarize here

Alternative designs not selected. 
Fractional
MRT
MACE-->





\newpage

# Literature Cited