---
title: "Make lapses tibble"
author: "John Curtin"
date: "3/28/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

### Notes



### Setup
```{r}
Sys.time()
library(tidyverse)
library(janitor)
library(ggthemes)
theme_set(theme_classic())

data_path <- "./shared/data"
```

### Final Sample
```{r}

final_sample <- read_rds(file.path(data_path, "final_sample.rds")) %>% 
  glimpse()

subids <- final_sample %>% 
  pull(subid) %>% 
  print() 

print(length(subids))

final_sample %>% 
  select(-subid) %>% 
  summarize_all(mean)
```

### Describe lapse overall

```{r}
lapses <- read_rds(file.path(data_path, "lapses.rds")) %>% 
  glimpse()


lapses%>% 
  tabyl(lapse)

lapses <- lapses %>% 
  group_by(subid) %>% 
  mutate(day = row_number()) %>% 
  ungroup() %>% 
  filter(day < 89)   #retained 89, 90,91 days for analysis but filtered for display b/c low number of cases

ggplot(data = lapses, aes(x = day, y = lapse)) +
  geom_jitter(height = .1) +
  stat_summary(aes(y = lapse), fun=mean, colour="red", geom="line", size = 1.5)
```

### Individual subject plots

```{r, fig.width = 10, fig.height = 200}
ggplot(data = lapses, aes(x = day, y = lapse)) +
  facet_wrap(vars(subid), ncol = 3) +
  geom_line(size = 1.5, color = "red") + 
  geom_point() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank())
```