---
title: "Make combined EMA"
author: "John Curtin"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = dplyr::if_else(Sys.info()[["sysname"]] == "Windows",
      "P:/studydata/risk/knits/insight", 
      "/Volumes/private/studydata/risk/knits/insight")
    )
  })
---

### Code Status

Complete

### Notes

Combines the morning and later ema files from shared folder and saves in processed data
for ema

Updated by GEF for Insight to include steps from mak_jobs as we will be making features locally

Absolute paths
```{r, absolute paths}
switch (Sys.info()[['sysname']],
        # PC paths
        Windows = {
          path_shared <- "P:/studydata/risk/data_processed/shared"
          path_insight <- "P:/studydata/risk/data_processed/insight"},
        
        # IOS paths
        Darwin = {
          path_shared <- "/Volumes/private/studydata/risk/data_processed/shared"
          path_insight <- "/Volumes/private/studydata/risk/data_processed/insight"}
)
```

Packages for lab workflow 
```{r, packages_workflow, message=FALSE, warning=FALSE}
library(conflicted) 
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
```


Packages for script
```{r, packages_script, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```


### Process and save ema
```{r}
ema_morning <- read_csv(file.path(path_shared, "ema_morning.csv"), 
                        show_col_types = FALSE) %>% 
  mutate(start_date = with_tz(start_date, tz = "America/Chicago"),
         end_date = with_tz(end_date, tz = "America/Chicago")) %>% 
  glimpse()

ema_later <- read_csv(file.path(path_shared, "ema_later.csv"), 
                      show_col_types = FALSE) %>% 
  mutate(start_date = with_tz(start_date, tz = "America/Chicago"),
         end_date = with_tz(end_date, tz = "America/Chicago")) %>%
  glimpse()
```

```{r}
ema <- ema_morning %>% 
  bind_rows(ema_later) %>% 
  mutate(subid = as.numeric(subid)) %>% 
  select(-response_id, -start_date, -finished, -status, -utc, 
         -send_date, -send_time, -ema_type, -ema_1, -ema_1_1, 
         -ema_1_2, -ema_1_3, -ema_1_4, -ema_1_5, -ema_1_6) %>% 
  rename(dttm_obs = end_date) %>% 
  arrange(subid, dttm_obs) %>% 
  glimpse()
```


```{r}
ema %>% 
  write_csv(file.path(path_insight, "ema.csv"))
```
