---
title: "Make demos.csv (from shared screen.csv) for features"
author: "Gaylen Fronk"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = dplyr::if_else(Sys.info()[["sysname"]] == "Windows",
      "P:/studydata/risk/knits/insight", 
      "/Volumes/private/studydata/risk/knits/insight")
    )
  })
---

### Code Status

This script updates mak_features_chtc.R to a) run locally, and b) work for project Insight

Absolute paths
```{r, absolute paths}
switch (Sys.info()[['sysname']],
        # PC paths
        Windows = {
          path_insight <- "P:/studydata/risk/data_processed/insight"
          path_shared <- "P:/studydata/risk/data_processed/shared"},
        
        # IOS paths
        Darwin = {
          path_insight <- "/Volumes/private/studydata/risk/data_processed/insight"
          path_shared <- "/Volumes/private/studydata/risk/data_processed/shared"}
)
```

Packages for lab workflow 
```{r, packages_workflow, message=FALSE, warning=FALSE}
library(conflicted) 
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
library(here) 
```

Packages for script
```{r, packages_script, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```

Read in screen.csv (shared demographics file)
```{r}
demos <- read_csv(here(path_shared, "screen.csv"),
                  show_col_types = FALSE) %>% 
  select(subid,
         demo_age = dem_1,
         demo_sex = dem_2,
         dem_3, dem_4,
         demo_educ = dem_5,
         demo_marital = dem_8) %>% 
  mutate(demo_race = if_else(str_detect(dem_3, "White/Caucasian"), 
                             "White/Caucasian", "Other"),
         demo_race = if_else(str_detect(dem_4, "Yes"), 
                             "Other", demo_race),
         demo_educ = str_replace(demo_educ, "High school or GED", 
                                 "High school or less"),
         demo_educ = str_replace(demo_educ, 
                                 "Less than high school or GED degree", 
                                 "High school or less"),
         demo_educ = str_replace(demo_educ, "2-Year degree", "Some college"),
         demo_educ = str_replace(demo_educ, 
                                 "College degree", "College or more"),
         demo_educ = str_replace(demo_educ, 
                                 "Advanced degree", "College or more"),
         demo_marital = str_replace(demo_marital, "Divorced", "Other"),
         demo_marital = str_replace(demo_marital, "Widowed", "Other"),
         demo_marital = str_replace(demo_marital, "Separated", "Other")) %>% 
  select(-dem_3, -dem_4) %>% 
  glimpse()
```

Write out
```{r}
demos %>% write_csv(here(path_insight, "demos.csv"))
```

