---
title: "intro hold"
format: html
---

# Introduction

<!--GEF overarching notes

i have added definitions of relapse (a goal-inconsistent return to substance use) and lapse (a single instance of goal-inconsistent substance use) the first time these terms are used per our group discussion. i will say that we seem to be using the terms somewhat interchangeably, which is perhaps ok until we start talking about our study, which should be specifically and exclusively about LAPSE risk. something to monitor in a final read.

i included potential subheadings in comments within the intro if we want to use them-->
 
Alcohol and other substance use disorders (SUDs) are highly prevalent and costly.  In 2019, the National Survey on Drug Use and Health estimated that over 20 million adults in the United States had some form of active SUD within that year [@substanceabuseandmentalhealthservicesadministrationKeySubstanceUse2020]. Nearly 15 million of those adults had an active alcohol use disorder (AUD) [@samhsa2019NationalSurvey; @samhsa2019NationalSurveyb].<!--KW: 2021 numbers are quite different when I compare the tables side by side. Past year SUD jumps to over 40 million, with nearly 30 million having AUD. There is a note in the table that says "Estimates from years prior to 2021 are not shown because of methodological changes in 2021" which likely explains this discrepancy. Should we use these more recent numbers?--> Furthermore, a substantial 25.8% of U.S. adults reported engaging in hazardous alcohol misuse within the past month <!--KW: 23.3% is 2021 estimate. Also note for context both of these estimates are reports of past month binge drinking--> [@samhsa2019NationalSurveya]. Alcohol ranks as the third leading preventable cause of death, accounting for approximately 140,000 fatalities per year [@centersfordiseasecontrolandpreventionAlcoholPublicHealth; @esserEstimatedDeathsAttributable2022]. In economic terms, the US Surgeon General disclosed that alcohol misuse cost the United States $249 billion in 2016 alone [@administrationusFacingAddictionAmerica2016].

Existing clinician-delivered treatments for AUD such as cognitive-behavioral therapy [@mchughCognitiveBehavioralTherapySubstance2010; @lieseCognitiveBehavioralTherapyAddictive2022], mindfulness-based relapse prevention [@bowenMindfulnessBasedRelapsePrevention2021; @goldbergMindfulnessbasedInterventionsPsychiatric2018], motivational interviewing [@millerMotivationalInterviewingHelping2012], and contingency management [@bigelowTheoreticalEmpiricalFoundations1999; @dutraMetaAnalyticReviewPsychosocial2008<!--can cut some refs eventually-->] are effective when provided to patients.  Unfortunately, fewer than 1 in 13 adults with an active AUD in 2019 received any treatment[@samhsa2019NationalSurveyc]<!--KW: in 2021 went from 7.5 to 4.6% (fewer than 1 in 20)-->.  Even more concerning, the failure to access treatment is associated with demographic factors including race, ethnicity, geographic region, and socioeconomic status, which further increase mental health disparities [@wangFailureDelayInitial2005; @MentalHealthReport1999; @generalusMentalHealthCulture2001; @mauraMentalHealthDisparities2017; @novakChangesHealthInsurance2018]. This treatment gap and associated disparities stem from well-known barriers to receiving clinician-delivered mental healthcare related to their affordability, accessibility, availability, and acceptability[@jacobsonUsingDigitalTherapeutics2023].

<!-- ## Digital Therapeutics Can Address Treatment Barriers -->

In recent years, digital therapeutics have emerged as an alternative method to deliver evidence-based treatments and other support to patients either independently or in conjunction with medications or clinician-administered mental healthcare[@jacobsonDigitalTherapeuticsMental2022 <!--Can re-use this reference later rather than chapters if needed to get cites <= 40-->]. Digital therapeutics are web-based or smartphone "apps" that are used to prevent, treat, or manage a medical disorder including AUD or other mental illnesses.  Several large randomized controlled trials have confirmed that digital therapeutics for alcohol or other SUDs improve clinical outcomes (e.g., abstinence, heavy drinking days[@gustafsonSmartphoneApplicationSupport2014; @campbellInternetdeliveredTreatmentSubstance2014]; see Campbell et al. [@campbellFirstWaveScalable2023] for review). They also may enhance treatment retention, reduce readmissions, and support engagement with medication-assisted treatments [@bottsMPOWERProjectResults2017; @japuntichSmokingCessationInternet2006; @pattenRandomizedClinicalTrial2006; @campbellInternetdeliveredTreatmentSubstance2014].

Digital therapeutics can mitigate or eliminate many of the affordability, accessibility, availability, and acceptability barriers associated with in-person, clinician-delivered mental healthcare because they are typically provided to patients on their smartphones[@jacobsonUsingDigitalTherapeutics2023].  Recent Pew Research Center survey data indicate high rates of smartphone ownership among US adults (approximately 85% in April 2021), with minimal variation across race, ethnicity, socioeconomic status, and geographic settings (e.g., urban, suburban, rural) [@pewresearchcenterMobileFactSheet2021]. Moreover, individuals with SUDs generally exhibit high rates of mobile technology use [@collinsFactorsAssociatedPatterns2016]. Consequently, digital therapeutics can offer highly scalable, on-demand therapeutic support that is accessible whenever and wherever it is needed most. 

<!--KW: Just noting the back and forth of focus on SUD, AUD, and mental health broadly in the intro. Since this was an issue with the burden reviewers we might want to consider whether we want to constrain our focus to SUD/AUD or even just AUD. -->


<!-- ## Improving Digital Therapeutics -->

Despite the documented clinical and other benefits of digital therapeutics, their full potential has not yet been realized because patients do not use them optimally.  Patients often don't engage with them as developers intended, and long-term engagement may not be sustained or matched to patients' needs [@hatchExpertConsensusSurvey2018; @lattieDigitalMentalHealth2019; @ngUserEngagementMental2019; @yeagerIfWeBuild2018].  The substantial benefits of digital therapeutics come from easy, 24/7 access to their many modules - their treatments, tools, and other support services.  However, this benefit also presents patients with a challenge.  They may be uncertain about when to use the app, which of the numerous modules within the app best suit their needs, and more specifically, which modules are most appropriate for their current situation.

Identifying these most appropriate modules can be difficult because of the dynamic nature of recovery from AUD over time. AUD is a chronic, relapsing disorder [@brandonRelapseRelapsePrevention2007; @witkiewitzModelingComplexityPosttreatment2007; @mclellanDrugDependenceChronic2000]<!--GEF: i moved the final clause of the previous paragraph into the beginning of this paragraph and split the topic sentence into two. didn't move any refs, so may need to move some refs to first sentence if they are about dynamic nature of recovery from AUD rather than AUD being a chronic relapsing disorder -->. Numerous risk and protective factors interact in complex, non-linear ways to influence the probability, timing, and severity of relapse (i.e., a goal-inconsistent return to substance use <!--KW: should we make this definition specific to alcohol use since this paragraph is now focussed on AUD?-->) [@hendershotRelapsePreventionAddictive2011; @witkiewitzRelapsePreventionAlcohol2004; @huffordRelapseNonlinearDynamic2003; @witkiewitzNonnormalityDivergencePosttreatment2007; @witkiewitzModelingComplexityPosttreatment2007]. Many of these factors are transient, leading to fluctuating relapse risk.  Factors such as urges, mood, lifestyle imbalances, self-efficacy, and motivation can all vary over time.  Social networks may evolve to be more protective or risky, and high risk situations can arise unexpectedly.

Clinical observations and research indicate that successful recovery necessitates life-long monitoring [@hendershotRelapsePreventionAddictive2011; @brandonRelapseRelapsePrevention2007; @huffordRelapseNonlinearDynamic2003; @witkiewitzTherapistGuideEvidenceBased2007; @witkiewitzModelingComplexityPosttreatment2007]. Continuous monitoring of risk for lapse (i.e., a single instance of goal-inconsistent substance use <!--KW: alcohol use? drinking?-->) and its contributing factors, if feasible, would enable patients to adapt their lifestyle, behaviors, and supports to their changing needs. In the context of digital therapeutic use, successful monitoring could direct patients to engage with the most appropriate specific modules in an app, addressing the unique risks present at any given moment throughout their recovery. This guided, adaptive engagement could potentially enhance the app's effectiveness. Thus far, however, the continuous, multi-factor monitoring required for this guidance has proved challenging due to the dynamic and complex interplay of various factors over time. <!--GEF: this final sentence was originally part of the first sentence; i felt it flowed better to talk about benefits and then end with not being able to do it yet since we then move into "but now we can!". didn't move any refs though so check if some from first sentence need to go here -->

<!--relevant review: mohrPersonalSensingUnderstanding2017-->
<!--KW: I think this paragraph below feels a little abrupt here. It might flow better if a subheading separates the above paragraph and this one? Also noting we are zooming out to mental health broadly again.--> 
Moment-by-moment personal sensing of intra- and interpersonal risk factors to support both long-term monitoring and forecasting of mental health functioning is now feasible[@epsteinPredictionStressDrug2020; @suchtingUsingElasticNet2019; @hebertPredictingFirstSmoking2021a; @engelhardPredictingSmokingEvents2018; @businelleUsingIntensiveLongitudinal2016; @soysterPooledPersonspecificMachine2022; @hebertEcologicalMomentaryIntervention2018; @moshontzProspectivePredictionLapses2021; @wyantAcceptabilityPersonalSensing2022; @chihPredictiveModelingAddiction2014; @baeMobilePhoneSensors2018]. Mohr et al. [@mohrPersonalSensingUnderstanding2017] define personal sensing as "collecting and analyzing raw data from sensors embedded in the context of daily life with the aim of identifying human behaviors, thoughts, feelings, and traits" <!--GEF: need a page number with a direct quotation-->. The widespread proliferation of smartphones has made personal sensing both powerful and practical.  Smartphones can be used for active sensing such as ecological momentary assessment (EMA; i.e., repeated, brief self-reports) and also passive, continuous sensing of geolocation, cellular communications (e.g., phone calls and text messages), activity level, sleep, and other raw signals that can predict meaningful clinical outcomes. 

<!-- ## EMA: A Powerful Sensing Tool -->

The current project focuses explicitly on the use of EMA to monitor lapse risk for both practical and strategic reasons. EMA can be easily implemented with only a smartphone; no additional hardware is necessary.  Moreover, comparable raw data (items and responses) can be used consistently across different hardware, operating systems, and sensing apps.  For these reasons, EMA can be incorporated essentially identically into any existing or future smartphone-based digital therapeutic.  EMA can support frequent, in situ longitudinal measurement that will likely be necessary for monitoring episodic or otherwise fluctuating relapse risk.  Long-term monitoring with EMA has been well-tolerated by individuals with SUD [@wyantAcceptabilityPersonalSensing2022; @moshontzProspectivePredictionLapses2021].  Previous research has validated the use of EMA to measure theoretically implicated risk and protective factors for relapse including craving [@dulinSmartphoneBasedMomentaryInterventionCraving2017], mood [@russellAffectRelativeDayLevelDrinking2020], stressors[@wemmDayByDayStressAlcohol], positive life events[@dvorakTensionReductionAffectReg2018], and motivation/efficacy [@dvorakEMAAcuteAUDSymptoms2014].  Furthermore, EMA provides privileged access to many of these more subjective constructs that may be difficult to quantify reliably through other sensing methods.  

Preliminary research is now emerging that uses EMA as features in machine learning models to predict the probability of future alcohol lapses or related outcomes [<!--Sarah - insert  refs-->].  This research is potentially important because it rigorously establishes temporal ordering between the predictors (features engineered from EMAs) and the outcomes. Additionally, the models are evaluated on data from participants that were not used to train the models, thus prioritizing model generalizability. Both these criteria are necessary to develop models that can be clinically useful to truly predict future lapses when implemented with new patients rather than simply confirm associations between putative risk factors and alcohol lapses among existing research participants.  

Despite this initial promise, several important gaps in this preliminary research restrict its generalizability and utility.  First, there are limitations regarding the samples used to train and evaluate these models.  Prediction models developed with samples such as college students or non-treatment-seeking hazardous drinking populations [e.g., <!--Sarah - insert college student or other convenience samples-->] provide important proof of concept; however, they may not generalize well to clinical samples of patients with AUD.  Similarly, models that have been developed to predict alcohol use in non-treatment seeking patients with AUD may be less clinically useful.  These individuals are unlikely to use digital therapeutics to support their recovery until they begin to contemplate and/or commit to behavior change regarding their alcohol use [<!--JJC to insert stage of change reference-->].  Moreover, features that predict planned or otherwise intentional alcohol use among individuals that are not motivated to change their behavior may not generalize to predict goal-inconsistent alcohol use (i.e., lapses) among patients in recovery.  

<!--Sarah - what about models predicting outcomes other than lapse (e.g., craving, stress)?  What can you tell us about those studies?

Added: Limited to studies that use EMA as a predictor, target SUD related outcomes (some smoking related...), utilized machine learning methods-->

<!--JOHN: review following paragraph re: including non-alcohol studies -->

A second limitation concerns the types of outcomes models are trained to predict. A handful of studies have trained models to predict precursors of substance use, such as craving [@burgess-hullTrajectoriesCravingMedicationassisted2022; @dumortierClassifyingSmokingUrges2016] and stress (Sarker et al., 2016). Although craving and stress are strongly associated with substance use, they do not reliably predict instances of substance use, limiting their utility for identifying specific instances for substance use treatment <!--GEF: probably need citations to make this claim, or make clear that the citations in the previous sentence are somehow supporting this-->. Moreover, due to the increased frequency of craving and stress events relative to substance use episodes, higher model performance can be achieved with less effort [@epsteinPredictionStressDrug2020] <!--GEF: "with less effort"?... is this about outcome class distribution? increased overall sample size? not quite sure what this means-->. Other studies have predicted temporally coarse clinical outcomes such as binary SUD treatment success [@acionUseMachineLearning2017; @coughlinMachineLearningApproachPredicting2020] or probability of treatment dropout for individuals in a medication-assisted treatment program for opioid use disorder [@gottliebMachineLearningPredicting2022]. These prediction models may be useful for identifying individuals who would benefit from increased SUD treatment; however, they do not provide enough temporal specificity to assist in identifying when resources should be directed to these individuals. <!--GEF: Sarah - I did my best to find the references you were citing & add them to Zotero; please double check that I found the studies you were thinking of! I was too uncertain about the Sarker 2016 paper to make a guess on that one.-->

<!--GEF: removed these two sentences from previous & just added citations to the second sentence - maintaining in case this level of detail is desired
For example, EMA has been demonstrated to predict levels of craving in individuals attempting to quit smoking (Durmortier et al 2016) as well as individuals in medication-assisted treatment programs for opioid use disorder (Burguess-Hall et al 2022). EMA combined with physiological data yielded prospective prediction of stressful event episodes in a small sample of individuals endorsing polysubstance use (Sarker et al 2016). 
-->


<!--JJC will justify lapse after we have above paragraph out other outcomes drafted.  - temporally precise, clearly defined, necessary for relapse, often early warning, can produce AVEs which can further undermine recovery. Abstinence is the FDA indicated outcome for clinical trials.  Describe here or in the current study below

GEF: took a stab at this below. My vote is for the paragraph to go here as I think it provides a good go-between from the previous paragraph about less than ideal outcomes to the next paragraph about the "exemplary" study that used lapses as outcome among other benefits.
-->

Predicting alcohol lapses (i.e., single instances of goal-inconsistent alcohol use) may be preferred for several reasons. First, a lapse is a drinking behavior rather than an associated factor or related behavior (e.g., craving, stress). Second, lapses are clearly defined and temporally precise. They have a specific onset and offset whose exact timing can be recorded; the lapse begins when drinking starts, and it ends when drinking stops. Lapses contrast with an outcome like relapse (i.e., returning to goal-inconsistent alcohol use), which cannot be clearly defined - it is unclear when a lapse becomes a relapse. However, the tight connection between lapses and relapses offers a third advantage in that a lapse is necessary for a relapse. Thus, lapses represent outcomes that precede relapses and may serve as early warnings for relapse. By building models that predict lapses, we position ourselves to assess risk for an event on which we can intervene before relapse. Fourth, lapses can produce adverse effects that could undermine recovery, making them clinically meaningful events that individuals pursuing recovery may wish to avoid. Finally, lapses represent events that are inconsistent with an abstinence goal. Abstinence not only remains a common goal among individuals in recovery from AUD but also is an FDA-indicated outcome for clinical trials. 

An early but exemplary prediction model developed by Gustafson et al. [@chihPredictiveModelingAddiction2014] provided the foundation on which our current project builds.  Participants enrolled in their study as they completed a residential treatment program for AUD.  Alcohol lapses were recorded for 8 months following program discharge while they received continuing care through the use of a digital therapeutic for AUD (A-CHESS). As such, the model was developed to predict a clinically meaningful outcome using individuals targeted for digital therapeutic use (i.e., clinical sample committed to AUD recovery-related behavior change).  However, the temporal precision for both the machine learning features and alcohol lapses was coarse because they were measured through a weekly survey.  Therefore, model predictions updated only once per week at best, and lapse onsets could occur anytime within the next two weeks.  This coarseness limits the utility of the model for "just-in-time" micro-interventions (e.g., guided mindfulness or other stress reduction techniques, urge surfing) that are well-suited to digital therapeutics but should be used in moments of peak risk. Furthermore, evaluation of this model should be considered both preliminary and optimistically biased because periods with missing surveys were excluded.  

<!-- ## Current Study -->

We designed the current study to address these gaps and limitations of previous machine learning prediction models from Gustafson [@chihPredictiveModelingAddiction2014] and others [<!--insert refs from above-->].  We developed our models using participants in early recovery (1-8 weeks since last alcohol use at study enrollment) from moderate to severe AUD who reported a goal of alcohol abstinence.  Consistent with this goal, these models predict future lapses back to alcohol use (i.e., instances of goal-inconsistent alcohol use).  We developed three separate models that provide hour-by-hour probabilities of a future lapse with increasing temporal precision (i.e., lapses in the next week, next day, and next hour, respectively).  Model features were based on raw and longitudinal change in theoretically-implicated risk factors[<!--insert relapse prevention model cites-->] derived from 4x daily EMAs. This research represents an important step toward the development of a "smart" (machine learning guided) sensing system that can both identify periods of peak lapse risk and recommend specific supports to address factors contributing to this risk.
# Introduction

<!--GEF overarching notes

i have added definitions of relapse (a goal-inconsistent return to substance use) and lapse (a single instance of goal-inconsistent substance use) the first time these terms are used per our group discussion. i will say that we seem to be using the terms somewhat interchangeably, which is perhaps ok until we start talking about our study, which should be specifically and exclusively about LAPSE risk. something to monitor in a final read.

i included potential subheadings in comments within the intro if we want to use them-->
 
Alcohol and other substance use disorders (SUDs) are highly prevalent and costly.  In 2019, the National Survey on Drug Use and Health estimated that over 20 million adults in the United States had some form of active SUD within that year [@substanceabuseandmentalhealthservicesadministrationKeySubstanceUse2020]. Nearly 15 million of those adults had an active alcohol use disorder (AUD) [@samhsa2019NationalSurvey; @samhsa2019NationalSurveyb].<!--KW: 2021 numbers are quite different when I compare the tables side by side. Past year SUD jumps to over 40 million, with nearly 30 million having AUD. There is a note in the table that says "Estimates from years prior to 2021 are not shown because of methodological changes in 2021" which likely explains this discrepancy. Should we use these more recent numbers?--> Furthermore, a substantial 25.8% of U.S. adults reported engaging in hazardous alcohol misuse within the past month <!--KW: 23.3% is 2021 estimate. Also note for context both of these estimates are reports of past month binge drinking--> [@samhsa2019NationalSurveya]. Alcohol ranks as the third leading preventable cause of death, accounting for approximately 140,000 fatalities per year [@centersfordiseasecontrolandpreventionAlcoholPublicHealth; @esserEstimatedDeathsAttributable2022]. In economic terms, the US Surgeon General disclosed that alcohol misuse cost the United States $249 billion in 2016 alone [@administrationusFacingAddictionAmerica2016].

Existing clinician-delivered treatments for AUD such as cognitive-behavioral therapy [@mchughCognitiveBehavioralTherapySubstance2010; @lieseCognitiveBehavioralTherapyAddictive2022], mindfulness-based relapse prevention [@bowenMindfulnessBasedRelapsePrevention2021; @goldbergMindfulnessbasedInterventionsPsychiatric2018], motivational interviewing [@millerMotivationalInterviewingHelping2012], and contingency management [@bigelowTheoreticalEmpiricalFoundations1999; @dutraMetaAnalyticReviewPsychosocial2008<!--can cut some refs eventually-->] are effective when provided to patients.  Unfortunately, fewer than 1 in 13 adults with an active AUD in 2019 received any treatment[@samhsa2019NationalSurveyc]<!--KW: in 2021 went from 7.5 to 4.6% (fewer than 1 in 20)-->.  Even more concerning, the failure to access treatment is associated with demographic factors including race, ethnicity, geographic region, and socioeconomic status, which further increase mental health disparities [@wangFailureDelayInitial2005; @MentalHealthReport1999; @generalusMentalHealthCulture2001; @mauraMentalHealthDisparities2017; @novakChangesHealthInsurance2018]. This treatment gap and associated disparities stem from well-known barriers to receiving clinician-delivered mental healthcare related to their affordability, accessibility, availability, and acceptability[@jacobsonUsingDigitalTherapeutics2023].

<!-- ## Digital Therapeutics Can Address Treatment Barriers -->

In recent years, digital therapeutics have emerged as an alternative method to deliver evidence-based treatments and other support to patients either independently or in conjunction with medications or clinician-administered mental healthcare[@jacobsonDigitalTherapeuticsMental2022 <!--Can re-use this reference later rather than chapters if needed to get cites <= 40-->]. Digital therapeutics are web-based or smartphone "apps" that are used to prevent, treat, or manage a medical disorder including AUD or other mental illnesses.  Several large randomized controlled trials have confirmed that digital therapeutics for alcohol or other SUDs improve clinical outcomes (e.g., abstinence, heavy drinking days[@gustafsonSmartphoneApplicationSupport2014; @campbellInternetdeliveredTreatmentSubstance2014]; see Campbell et al. [@campbellFirstWaveScalable2023] for review). They also may enhance treatment retention, reduce readmissions, and support engagement with medication-assisted treatments [@bottsMPOWERProjectResults2017; @japuntichSmokingCessationInternet2006; @pattenRandomizedClinicalTrial2006; @campbellInternetdeliveredTreatmentSubstance2014].

Digital therapeutics can mitigate or eliminate many of the affordability, accessibility, availability, and acceptability barriers associated with in-person, clinician-delivered mental healthcare because they are typically provided to patients on their smartphones[@jacobsonUsingDigitalTherapeutics2023].  Recent Pew Research Center survey data indicate high rates of smartphone ownership among US adults (approximately 85% in April 2021), with minimal variation across race, ethnicity, socioeconomic status, and geographic settings (e.g., urban, suburban, rural) [@pewresearchcenterMobileFactSheet2021]. Moreover, individuals with SUDs generally exhibit high rates of mobile technology use [@collinsFactorsAssociatedPatterns2016]. Consequently, digital therapeutics can offer highly scalable, on-demand therapeutic support that is accessible whenever and wherever it is needed most. 

<!--KW: Just noting the back and forth of focus on SUD, AUD, and mental health broadly in the intro. Since this was an issue with the burden reviewers we might want to consider whether we want to constrain our focus to SUD/AUD or even just AUD. -->


<!-- ## Improving Digital Therapeutics -->

Despite the documented clinical and other benefits of digital therapeutics, their full potential has not yet been realized because patients do not use them optimally.  Patients often don't engage with them as developers intended, and long-term engagement may not be sustained or matched to patients' needs [@hatchExpertConsensusSurvey2018; @lattieDigitalMentalHealth2019; @ngUserEngagementMental2019; @yeagerIfWeBuild2018].  The substantial benefits of digital therapeutics come from easy, 24/7 access to their many modules - their treatments, tools, and other support services.  However, this benefit also presents patients with a challenge.  They may be uncertain about when to use the app, which of the numerous modules within the app best suit their needs, and more specifically, which modules are most appropriate for their current situation.

Identifying these most appropriate modules can be difficult because of the dynamic nature of recovery from AUD over time. AUD is a chronic, relapsing disorder [@brandonRelapseRelapsePrevention2007; @witkiewitzModelingComplexityPosttreatment2007; @mclellanDrugDependenceChronic2000]<!--GEF: i moved the final clause of the previous paragraph into the beginning of this paragraph and split the topic sentence into two. didn't move any refs, so may need to move some refs to first sentence if they are about dynamic nature of recovery from AUD rather than AUD being a chronic relapsing disorder -->. Numerous risk and protective factors interact in complex, non-linear ways to influence the probability, timing, and severity of relapse (i.e., a goal-inconsistent return to substance use <!--KW: should we make this definition specific to alcohol use since this paragraph is now focussed on AUD?-->) [@hendershotRelapsePreventionAddictive2011; @witkiewitzRelapsePreventionAlcohol2004; @huffordRelapseNonlinearDynamic2003; @witkiewitzNonnormalityDivergencePosttreatment2007; @witkiewitzModelingComplexityPosttreatment2007]. Many of these factors are transient, leading to fluctuating relapse risk.  Factors such as urges, mood, lifestyle imbalances, self-efficacy, and motivation can all vary over time.  Social networks may evolve to be more protective or risky, and high risk situations can arise unexpectedly.

Clinical observations and research indicate that successful recovery necessitates life-long monitoring [@hendershotRelapsePreventionAddictive2011; @brandonRelapseRelapsePrevention2007; @huffordRelapseNonlinearDynamic2003; @witkiewitzTherapistGuideEvidenceBased2007; @witkiewitzModelingComplexityPosttreatment2007]. Continuous monitoring of risk for lapse (i.e., a single instance of goal-inconsistent substance use <!--KW: alcohol use? drinking?-->) and its contributing factors, if feasible, would enable patients to adapt their lifestyle, behaviors, and supports to their changing needs. In the context of digital therapeutic use, successful monitoring could direct patients to engage with the most appropriate specific modules in an app, addressing the unique risks present at any given moment throughout their recovery. This guided, adaptive engagement could potentially enhance the app's effectiveness. Thus far, however, the continuous, multi-factor monitoring required for this guidance has proved challenging due to the dynamic and complex interplay of various factors over time. <!--GEF: this final sentence was originally part of the first sentence; i felt it flowed better to talk about benefits and then end with not being able to do it yet since we then move into "but now we can!". didn't move any refs though so check if some from first sentence need to go here -->

<!--relevant review: mohrPersonalSensingUnderstanding2017-->
<!--KW: I think this paragraph below feels a little abrupt here. It might flow better if a subheading separates the above paragraph and this one? Also noting we are zooming out to mental health broadly again.--> 
Moment-by-moment personal sensing of intra- and interpersonal risk factors to support both long-term monitoring and forecasting of mental health functioning is now feasible[@epsteinPredictionStressDrug2020; @suchtingUsingElasticNet2019; @hebertPredictingFirstSmoking2021a; @engelhardPredictingSmokingEvents2018; @businelleUsingIntensiveLongitudinal2016; @soysterPooledPersonspecificMachine2022; @hebertEcologicalMomentaryIntervention2018; @moshontzProspectivePredictionLapses2021; @wyantAcceptabilityPersonalSensing2022; @chihPredictiveModelingAddiction2014; @baeMobilePhoneSensors2018]. Mohr et al. [@mohrPersonalSensingUnderstanding2017] define personal sensing as "collecting and analyzing raw data from sensors embedded in the context of daily life with the aim of identifying human behaviors, thoughts, feelings, and traits" <!--GEF: need a page number with a direct quotation-->. The widespread proliferation of smartphones has made personal sensing both powerful and practical.  Smartphones can be used for active sensing such as ecological momentary assessment (EMA; i.e., repeated, brief self-reports) and also passive, continuous sensing of geolocation, cellular communications (e.g., phone calls and text messages), activity level, sleep, and other raw signals that can predict meaningful clinical outcomes. 

<!-- ## EMA: A Powerful Sensing Tool -->

The current project focuses explicitly on the use of EMA to monitor lapse risk for both practical and strategic reasons. EMA can be easily implemented with only a smartphone; no additional hardware is necessary.  Moreover, comparable raw data (items and responses) can be used consistently across different hardware, operating systems, and sensing apps.  For these reasons, EMA can be incorporated essentially identically into any existing or future smartphone-based digital therapeutic.  EMA can support frequent, in situ longitudinal measurement that will likely be necessary for monitoring episodic or otherwise fluctuating relapse risk.  Long-term monitoring with EMA has been well-tolerated by individuals with SUD [@wyantAcceptabilityPersonalSensing2022; @moshontzProspectivePredictionLapses2021].  Previous research has validated the use of EMA to measure theoretically implicated risk and protective factors for relapse including craving [@dulinSmartphoneBasedMomentaryInterventionCraving2017], mood [@russellAffectRelativeDayLevelDrinking2020], stressors[@wemmDayByDayStressAlcohol], positive life events[@dvorakTensionReductionAffectReg2018], and motivation/efficacy [@dvorakEMAAcuteAUDSymptoms2014].  Furthermore, EMA provides privileged access to many of these more subjective constructs that may be difficult to quantify reliably through other sensing methods.  

Preliminary research is now emerging that uses EMA as features in machine learning models to predict the probability of future alcohol lapses or related outcomes [<!--Sarah - insert  refs-->].  This research is potentially important because it rigorously establishes temporal ordering between the predictors (features engineered from EMAs) and the outcomes. Additionally, the models are evaluated on data from participants that were not used to train the models, thus prioritizing model generalizability. Both these criteria are necessary to develop models that can be clinically useful to truly predict future lapses when implemented with new patients rather than simply confirm associations between putative risk factors and alcohol lapses among existing research participants.  

Despite this initial promise, several important gaps in this preliminary research restrict its generalizability and utility.  First, there are limitations regarding the samples used to train and evaluate these models.  Prediction models developed with samples such as college students or non-treatment-seeking hazardous drinking populations [e.g., <!--Sarah - insert college student or other convenience samples-->] provide important proof of concept; however, they may not generalize well to clinical samples of patients with AUD.  Similarly, models that have been developed to predict alcohol use in non-treatment seeking patients with AUD may be less clinically useful.  These individuals are unlikely to use digital therapeutics to support their recovery until they begin to contemplate and/or commit to behavior change regarding their alcohol use [<!--JJC to insert stage of change reference-->].  Moreover, features that predict planned or otherwise intentional alcohol use among individuals that are not motivated to change their behavior may not generalize to predict goal-inconsistent alcohol use (i.e., lapses) among patients in recovery.  

<!--Sarah - what about models predicting outcomes other than lapse (e.g., craving, stress)?  What can you tell us about those studies?

Added: Limited to studies that use EMA as a predictor, target SUD related outcomes (some smoking related...), utilized machine learning methods-->

<!--JOHN: review following paragraph re: including non-alcohol studies -->

A second limitation concerns the types of outcomes models are trained to predict. A handful of studies have trained models to predict precursors of substance use, such as craving [@burgess-hullTrajectoriesCravingMedicationassisted2022; @dumortierClassifyingSmokingUrges2016] and stress (Sarker et al., 2016). Although craving and stress are strongly associated with substance use, they do not reliably predict instances of substance use, limiting their utility for identifying specific instances for substance use treatment <!--GEF: probably need citations to make this claim, or make clear that the citations in the previous sentence are somehow supporting this-->. Moreover, due to the increased frequency of craving and stress events relative to substance use episodes, higher model performance can be achieved with less effort [@epsteinPredictionStressDrug2020] <!--GEF: "with less effort"?... is this about outcome class distribution? increased overall sample size? not quite sure what this means-->. Other studies have predicted temporally coarse clinical outcomes such as binary SUD treatment success [@acionUseMachineLearning2017; @coughlinMachineLearningApproachPredicting2020] or probability of treatment dropout for individuals in a medication-assisted treatment program for opioid use disorder [@gottliebMachineLearningPredicting2022]. These prediction models may be useful for identifying individuals who would benefit from increased SUD treatment; however, they do not provide enough temporal specificity to assist in identifying when resources should be directed to these individuals. <!--GEF: Sarah - I did my best to find the references you were citing & add them to Zotero; please double check that I found the studies you were thinking of! I was too uncertain about the Sarker 2016 paper to make a guess on that one.-->

<!--GEF: removed these two sentences from previous & just added citations to the second sentence - maintaining in case this level of detail is desired
For example, EMA has been demonstrated to predict levels of craving in individuals attempting to quit smoking (Durmortier et al 2016) as well as individuals in medication-assisted treatment programs for opioid use disorder (Burguess-Hall et al 2022). EMA combined with physiological data yielded prospective prediction of stressful event episodes in a small sample of individuals endorsing polysubstance use (Sarker et al 2016). 
-->


<!--JJC will justify lapse after we have above paragraph out other outcomes drafted.  - temporally precise, clearly defined, necessary for relapse, often early warning, can produce AVEs which can further undermine recovery. Abstinence is the FDA indicated outcome for clinical trials.  Describe here or in the current study below

GEF: took a stab at this below. My vote is for the paragraph to go here as I think it provides a good go-between from the previous paragraph about less than ideal outcomes to the next paragraph about the "exemplary" study that used lapses as outcome among other benefits.
-->

Predicting alcohol lapses (i.e., single instances of goal-inconsistent alcohol use) may be preferred for several reasons. First, a lapse is a drinking behavior rather than an associated factor or related behavior (e.g., craving, stress). Second, lapses are clearly defined and temporally precise. They have a specific onset and offset whose exact timing can be recorded; the lapse begins when drinking starts, and it ends when drinking stops. Lapses contrast with an outcome like relapse (i.e., returning to goal-inconsistent alcohol use), which cannot be clearly defined - it is unclear when a lapse becomes a relapse. However, the tight connection between lapses and relapses offers a third advantage in that a lapse is necessary for a relapse. Thus, lapses represent outcomes that precede relapses and may serve as early warnings for relapse. By building models that predict lapses, we position ourselves to assess risk for an event on which we can intervene before relapse. Fourth, lapses can produce adverse effects that could undermine recovery, making them clinically meaningful events that individuals pursuing recovery may wish to avoid. Finally, lapses represent events that are inconsistent with an abstinence goal. Abstinence not only remains a common goal among individuals in recovery from AUD but also is an FDA-indicated outcome for clinical trials. 

An early but exemplary prediction model developed by Gustafson et al. [@chihPredictiveModelingAddiction2014] provided the foundation on which our current project builds.  Participants enrolled in their study as they completed a residential treatment program for AUD.  Alcohol lapses were recorded for 8 months following program discharge while they received continuing care through the use of a digital therapeutic for AUD (A-CHESS). As such, the model was developed to predict a clinically meaningful outcome using individuals targeted for digital therapeutic use (i.e., clinical sample committed to AUD recovery-related behavior change).  However, the temporal precision for both the machine learning features and alcohol lapses was coarse because they were measured through a weekly survey.  Therefore, model predictions updated only once per week at best, and lapse onsets could occur anytime within the next two weeks.  This coarseness limits the utility of the model for "just-in-time" micro-interventions (e.g., guided mindfulness or other stress reduction techniques, urge surfing) that are well-suited to digital therapeutics but should be used in moments of peak risk. Furthermore, evaluation of this model should be considered both preliminary and optimistically biased because periods with missing surveys were excluded.  

<!-- ## Current Study -->

We designed the current study to address these gaps and limitations of previous machine learning prediction models from Gustafson [@chihPredictiveModelingAddiction2014] and others [<!--insert refs from above-->].  We developed our models using participants in early recovery (1-8 weeks since last alcohol use at study enrollment) from moderate to severe AUD who reported a goal of alcohol abstinence.  Consistent with this goal, these models predict future lapses back to alcohol use (i.e., instances of goal-inconsistent alcohol use).  We developed three separate models that provide hour-by-hour probabilities of a future lapse with increasing temporal precision (i.e., lapses in the next week, next day, and next hour, respectively).  Model features were based on raw and longitudinal change in theoretically-implicated risk factors[<!--insert relapse prevention model cites-->] derived from 4x daily EMAs. This research represents an important step toward the development of a "smart" (machine learning guided) sensing system that can both identify periods of peak lapse risk and recommend specific supports to address factors contributing to this risk.
