---
output:
  pdf_document:
    includes:
      in_header: header.tex 
    template: nih_latex_template.tex
    fig_caption: yes
    keep_tex: no
    number_sections: no
    latex_engine: xelatex
    citation_package: default
  word_document: 
    reference_docx: nih_word_template.docx
csl: national-library-of-medicine-grant-proposals.csl
geometry: margin=.5in
mainfont: Arial
fontsize: 11pt
bibliography: paper_ema.bib
---

```{r, setup, echo = FALSE, include=FALSE}
library(tidyverse)
library(kableExtra)
library(flextable)
library(officer)
```

# Introduction

## AUD treatment difficulty and barriers

Alcohol Use Disorder (AUD) is a highly prevalent, costly, relapsing disease which presents multiple difficulties for treatment. An estimated 14.5 million adults in the United States meet criteria for AUD within the past year. The consequences of AUD are linked to serious health and safety problems for the individual, as well as hefty societal costs (higher rates of crime, elevated healthcare spending). Over 140,000 deaths in the US each year are alcohol related, and rates of alcohol related hospitalizations rose by 47% between 2010 and 2014, highlighting the severity and increasing public  health risk associated with AUD. Despite these salient negative consequences, only 13% of individuals with AUD seek treatment. Issues of stigma, cost, burden, and limited availability greatly reduce the ability of an individual with AUD to obtain treatment.

<!--KW: Not sure the last sentence is needed if we narrow the scope of the intro to just include:
    1. AUD is a prevalent, costly, relapsing disease.
    2. The complexity of AUD calls for individualized, dynamic, and sustainable treatments.
    3. Temporally precise prediction is needed to do this
    4. Our study demonstrates this can be done with EMA
-->


Even for those who do obtain treatment, the complex and relapsing nature of AUD results in a difficult treatment process. This complexity is modeled by contemporary relapse prevention models of substance use treatment that stress the inidividualized, dynamic, and context dependent nature of relapse events which requires tailored treatment and sustained efforts towards personal wellness on the the part of the individual.  Individuals in treatment for AUD tend to relapse often and unexpectedly requiring life long monitoring. While contemporary relapse prevention and biopsychosocial models of substance use treatment aknowledge the ongoing complexity associated with relapse, the burden of monitoring this complexity has typically fallen on the individual recieving treatment. Previous research has identified that individuals with AUD  are often unable to recognize when states risk or opportunity for intervention emerge, and fail to initiate the type of support needed to address these states in a timely manner. While relapse prevention techniques have been effective at identifying the utility of different skill sets for different relapse situations, the effort of self-monitoring for increased risky situations during which to use these interventions is left to the individual, creating frequent opportunties for relapse in the recovery process.

Digital therapeudics holds potential to address issues of AUD treatment accesibility and complexity. Broadly, digital therapeudics refers to a treatment framework utilizing mobile health technology (e.g. smartphones, wearable devices) to deliver mental health interventions in a low cost, scalable manner. Digital therapeudics can address many barriers related to low levels of treatment seeking in individuals with AUD due to the low burden on the part of the participant to access treatment on a digital platform. Emerging digital therapeudics have been sucessful in reducing substance use disorder related outcomes, including increased abstinence levels, decreased heavy drinking days, and increased retention in treatment programs among individuals in treatment for alcohol, marajuana, cocaine, and polysubstance use. Previous work has demonstrated the acceptability of mobile health interventions among individuals with substance use disorders, and multiple studies have assessed their efficacy in populations that are typically difficulty to engage in treatmet for AUD (e.g. rural communities, homeless populations). <!--GEF: i think this paragraph can be shortened a lot - its main purpose (from my understanding) in the intro is to set the scene for digital therapeutics as a sensing and monitoring platform. more details can happen about opportunities for treatment in the discussion --> 
<!--KW: I think this paragraph could be removed-->

Digital therapeudics also offer a platform to address the complexity of AUD treatment to remove burden from the individual during the treatment process. Less work has examined the ability for digital therapeudics to increase treatment efficacy by tailoring interventions to the complex nature of AUD. Calls for development of just-in-time  adpative interventions (JITAIS) <!--GEF: i know you were excited about the JITAI terminology. personally i find it distracting (at least in the intro) given that this project is several steps away from JITAI development. maybe good to bring in during the discussion? -->within digital therapeudics for substance use disorder have identified this gap in emerging mobile health literature; while technology is rapidly advancing to monitor the complex nature of AUD, mobile health interventions are not currently incorportating these abilities into treatments for AUD. Nahum-Shami and peers suggest utilization of JITAIS via an "intervention-determined" approach, where individuals are monitored for decision rules where certain treatment techniques should be applied. This approach easily lends itself to incorportation of the AUD complexity discussed in contemporary relapse prevention models, where the proximal and distal factors leading up to a lapse in recovery are essential to tailoring the content and timing of specific interventions. <!--GEF: similarly, i think this paragraph can be shortened in combination with the previous paragraph to get across the two main points (which are basically your two topic sentences) --> 
<!--KW: I think this paragrpah could be narrowed down to a sentence or two. Just providing some context for what a prediction algorithm could be used for without going to in-depth.-->

<!--GEF: more broadly my reaction to this first section - i think that these previous two paragraphs are distracting me from the point of this project. i feel like the final sentence of paragraph 2 (about the effort of self-monitoring leading to frequent lapses/relapses during recovery) connects well to this following section, about what we need to be able to identify moments of high risk for lapse - in essence, to do the monitoring FOR them. i'm not sure if re-organization would help, or if just greatly minimizing these previous two paragraphs would keep things more in line with the current project? -->

 ## Dynamic, personalized prediction of lapse
 
The first step in development of these JITAs is to identify crucial windows of time leading up to lapses where treatment should be deployed. Temporally precise prediction of lapse requires two components: frequently monitored, contextually rich data about the individuals state and environment, and an analytic method that can handle the complexity multiple multifaceted factors to make predictions.

<!-- KW: maybe add a sentence or two introducing EMA as a source of "frequently monitored, contextually rich data"-->

Previous work utilizing ecological momentary assessment (EMA) has identified key associations between an individual's environment and lapse. An established repository of past work has identified relationships between person and context specific factors measured via EMA and substance use outcomes. For example, proximal stress has been demonstrated to have a stronger association with drinking than daily ratings of stress. However, this work has also hilighted the nuances of associations between EMA and alcohol use and their subsequent difficulty in making prospective predictions of lapse. Studies have found that both negative and positive mood events associated with an increased risk of substance use. To capture these nuances, prospective, temporally precise prediction of lapses will likely require incorporation of multiple variables associated with use and their interactions among eachother at a given time. <!-- GEF: i like the idea here of noting the well-established literature using EMA to establish relationships between alcohol use/AUD and context factors. i think the argument could flow more persuasively if you introduced that literature first (stress, neg/pos mood), THEN transitioned to the idea that those associations don't always translate to true prediction, which is what we need if we want to monitor lapse risk and have a hope of intervening. maybe even two (brief) separate paragraphs-->

Emerging work has incorporated machine learning methods to make temporally precise prediction of substance use and related outcomes. <!--GEF: why is this needed? maybe important to emphasize/remind readers that ML can handle high-dimensional data, which is necessary when the factors that affect risk and recovery are many-fold and vary greatly between people and within a person over time. and also that inherent to ML is the idea of predicting into new data, which supports generalizability of models and ultimate application of these algorithms to new patients beyond research settings-->
•	To provide support in real time, we need true prediction
•	Machine learning methods can handle the complexity of data needed for precise temporal prediction
•	Emerging work using machine learning methods to predict substance use related outcomes is promising
•	Limitations of current research
•	Short windows of data collection
•	Small N designs
•	Non-clinical samples

## Current project
The current project can address treatment barriers <!--GEF: i'd vote for an alternative, narrrower framing of the purpose of the current project. it's about learning whether we can predict lapses prospectively using EMA data - about whether we can monitor patients' risk rather than asking them to self-monitor. addressing treatment barriers feels pretty big --> 
<!--KW: I would maybe remove emphasis on treatment barriers if we need to narrow scope. Instead maybe focus on complexity?-->
•	Utilize EMA in a predictive framework to identify when lapses will occur
•	Remove requirement for individuals to independently monitor changes in risk <!--KW: this might be outside the scope of our study-->
•	Data collection and analysis framework provides depth of data required for these predictions
* Large N, clinical sample, long windows of data collection <!--GEF: highlight that these are improvements designed to address limitations of existing, promising research using ML for SUD outcomes -->
