---
output:
  pdf_document:
    includes:
      in_header: !expr here::here("..", "lab_support", "rmd_templates", "latex", "header.tex")
    template: !expr here::here("..", "lab_support", "rmd_templates", "latex", "nih_latex_template.tex")
    keep_tex: no
    number_sections: no
    latex_engine: xelatex
    citation_package: default
header-includes:
  - \usepackage{helvet}
  - \usepackage[T1]{fontenc}
  - \renewcommand\familydefault{\sfdefault}
geometry: margin=.5in
fontsize: 11pt
---

Dear Dr. Buis,

We are pleased to submit a revised version of our manuscript "Acceptability of personal sensing among people with alcohol use disorder: Observational study" (Manuscript No. JMU 41833) for editorial review at JMIR mHealth and uHealth. Below, we delineate the reviewer’s and action editor’s questions, concerns, and requests regarding our revised submission, and we detail the ways in which we have addressed each item.

Sincerely,

Kendra Wyant, Hannah Moshontz, Stephanie Ward, Gaylen Fronk, & John Curtin

---




# Action Editor's Comments

## AE.1: Please note that as indicated in the checklist above, this paper is very long and will likely incur additional fees for copyediting. Please see the following link for more info: https://support.jmir.org/hc/en-us/articles/115002798327

We have moved Table 4 (sample free-response comments from participants by theme) to Multimedia Appendix 3 due to its length. We now provide parenthetical examples in the results section of each theme. We acknowledge our word count is still above the recommended 10,000 words and are willing to pay additional copyediting fees if incurred.


# Reviewer O Comments:

## RO.4: Background provides a good overview of the use of mobile sensors in psychiatry. But it is sometimes unclear when the statements refer to alcohol or substance use and what is more general in mental health.
We have edited the introduction to clearly identify when we are reviewing/citing studies that refer to samples with broader psychiatric disorders vs. narrower alcohol and other substance use disorders.   
-- Thank you for addressing this. I think it could be further improved by more clearly state which areas/types of sensing have been studied for substance use. For example in the following only ref 13 and 15 seem to be regarding substance use?: "More recently, research using personal sensing of raw data streams other than self-report is emerging for mental health broadly, including alcohol and other substance use disorders. This includes methods to sense geolocation [13–15], cellular communications [15–19], sleep [19], and physiology [20,21], as examples." And in the following eight references on different substances and aims are all thrown in together: "For alcohol and other substance use disorders, research is emerging now to used sensed data to predict craving, alcohol, cannabis, or opioid use, and lapses/relapse [13,29–36]"
--- We have added additional substance use references (29-32,35) to the characterization of different personal sensing methods. Additionally, we now break apart the substance use references to be more clear about each study's outcome (i.e., craving, use, lapses/relapse).
---- Ok, if I read your 4th paragraph right, there is now 5 or more references to some of the statements. Could you clean that up and choose the most relevant ones that illustrate that each method have been used for substance use?

-----
We have reduced the number of references for each personal sensing method,and limited citations to those narrowly focused on substance use. 


## RO.6: What previous research have been made on the different sensing methods for alcohol use disorder? (Bae 2018, Stevenson 2020, Scott 2020…)
We have expanded our review of sensing methods for alcohol and other substance use disorder.  This expanded review includes the papers cited here along with other relevant papers.  See point RB.2 above.    
-- Thank you for adding more recent references. It is still not possible to get a clear picture of the knowledge on different methods for alcohol specifically from your introduction.
--- We have broken up the references to be more clear about which are related to alcohol specifically (29-31,33). See point RO.4 above.  We have not opted to further expand the review of the literature in the introduction as the editor has already noted that our paper is longer than typical for this journal.  The goal of the introduction was simply to provide a framework for the study; this paper is not intended to be a stand-alone review.
---- Thank you. I agree that it is long. I do not suggest expanding it, rather the opposite. but maybe try to make it more specific to what is relevant to your study.

-----
We have addressed this by limiting our review of sensing methods in paragraph 4 to focus only on substance use (see point RO.4 above). 
