---
title: "Cellular Communication Notes"
author: "Kendra Wyant"
output: html_document
---

## 009

- Subject’s SMS files are empty because the subject deleted all text messages before their study visit; They also did not text much.  


## 027 

- Unable to get unreported contacts at FU #1 as the R script was not working properly.   





## 032

- Participant bought a new phone in the first month of the study and so we collected call/sms logs from both phones at Follow Up 1.   


## 034

- Has only 2 Voice/sms files as they missed their Follow up 2 appointment therefore staff was only able to retrieve the logs at Follow Up 1 and Follow Up 3.  


## 052

- At followup 1 participant had very few text messages because they forgot to keep their messages and so they were just deleting them. The participant was reminded that we collect that info as part of their study participation and that we would like them to not delete texts that they feel comfortable sharing. They forgot to bring their old phone to followup one but they brought it to FU2 where voice and SMS logs were downloaded.    


## 056 

- 05/09/2018: Due to an error in the messages script when Call and SMS logs were transferred unreported contacts were not able to be reported at their Follow-up 1. One of their text messages did not have a handle_id so it could not be linked to a phone number. They will be collected at Follow-up 2.    


## 066

- RA does not trust the contacts data given at FU #2 and FU#3. The participant seemed to be in a rush and marked several contacts irrelevant/spam and neglected to answer the contact follow-up questions when asked directly by RA
- From FU3 session form - RA does not believe the participant gave quality data. She marked irrelevant spam for all of the unreported contacts she was asked about. Additionally, RA only had the opportunity to review one unreported contact because the participant had to leave to go to work. She arrived 20 minutes late for her visit and had to leave 40 minutes later, so we did not have time to complete the appointment. The participant did not tell RA ahead of time that she only had a short time to meet.


## 074

- Unable to retrieve the phone and text message logs from the participant at Follow-up 1 since their phone is broken and will not turn on. The SMS and voice files are on their phone but will have to be missing data.   

## 081

- Participant’s partner is incarcerated. She reported that all of the phone calls that come up as restricted or unknown are incoming calls from her partner. She reported that she speaks to him frequently.   


## 082

- Participant only has 1 call and 1 SMS log due to reported stolen phone   


## 084 

- Participant didn’t have many phone calls or text messages    


## 130

- Unable to run Unreported Contacts at both Follow-up 1 and 2 due to error in R from participants SMS logs. Resolved by Follow-up 3 and Unreported Contacts were reported; There will only be SMS and Voice files for visits _1 and _3. This is correct and still captures 90 full days of data even though there are only 64 distinct days with observations for Voice (<1 call made per day).   

## 135 

- Participant is missing Call and SMS logs for their Final Visit due to their phone having been reported lost/stolen shortly before their final visit date.   


## 138

- Participant only has 4 Voice files once compliance is run for All. This seems to be accurate due to the participants small Voice transfer files and low number of unreported contacts at each follow-up visit.  


## 161 

- Since participant got a new phone before their Followup1 they brought both phones to their visit. Both phones were backed up with the new phone producing the two files and the old producing one.   
- Took FU2 survey from home. Unreported contacts for FU2 and FU3 collected at final visit.  


## 162

- Participant was unable to reschedule their Follow up 2 appointment therefore there will only be 2 Voice and SMS files in their raw data folder.  


## 166

- according to data log 4 contact numbers were removed because they were duplicates. Exact information listed in logs.

## 167

- Staff were unable to tether participants phone to the laptop at the time of their follow-up 1 visit but were able to email Call and SMS logs to study email and download them from there; At Follow-up Visits 2&3 staff had to share SMS Backup and Restore downloads via the participants Google Drive as the files were too large to email. This method was effective and the files were transferred and permanently deleted from the laptop and Google Drive account.  
- According to data log one duplicate contact entry was removed from the contacts excel file. Information about this contact is in the subid's data log.


## 169

- Participant was concerned about cell phone text and call log collection   


## 179

- Data log contains information about some duplicate contacts removed from their contacts excel file.   
- Subid talks to two different parents on phone number with contact_type labeled parent.    

## 183

- One duplicate contact under spouse/significant other removed from contacts excel file. Information about this is in the subid's raw data log file.   

## 185

- Duplicate #s 608-837-4717 and 608-332-7157 were removed from the participant’s contact spreadsheet.   

## 188

- One duplicate contact removed from contact file. Information in subid's raw data file.   

## 190

- No contacts or locations to report at FU3 - Contacts were not necessarily irrelevant/spam, but participant did not want to answer questions about them.   


## 192

- Two duplicate contacts removed from contacts excel file. Details about duplicates in subid's data log.   


## 201

- The participant only has 2 SMS and Voice files in her raw data folder because she did not come into the lab for a F2 visit.   
- The participant got a new telephone a couple weeks before she completed the study. She did not bring her old phone with her to her final study visit so we were unable to obtain any voice and sms files from her old phone.   


## 204

- Five duplicate contacts removed from contacts excel file. Removed contacts documented in subid's data log file.  

## 207

- Participant sees clients confidentially and does not want their data used for the study so some of the irrelevant/spam numbers are client phone numbers.  
- One duplicate number removed from contacts excel file. Information documented in subid's data log.


## 208

- One duplicate number removed from contacts excel file. Information documented in subid's data log.   


## 211

- SMS logs were collected at Follow up 1 but due to the messaging app that the participant was using we were unable to get SMS data past a certain data. The participant switched messaging apps to the default so we will hopefully get that info at Follow up 2.   


## 212

- Participant already uses SMS Backup at Intake. He stated that he cannot backup to his phone because he has like 7 google accounts and 20K text messages being backed up. He offered to bring his backups in on a memory key, or to log into the cloud on a computer and download to our server directly.    

## 213

- Participant reported having a family stay with him while he was on study. At times they would use participant’s cell phone so often numbers that came up in his logs were unknown to him and were recorded as spam.     


## 221

- Participant had a lot of unreported contacts. RAs did not go over all of them at FU1 due to lack of participant time and RA was planning on going over them at FU2. Participant was in contact with several people that she also visited at their homes-RA did not connect the contact number with the locations and was planning on collecting this at FU2. Participant no-showed at FU2.    


## 223

- Participant got a new phone and phone number so they came in on 5/20/2019 to get apps put on their phone and to register for surveys. Participant brought their deactivated phone with to delete apps and to transfer calls and SMS files (labeled SMS_1 and Calls_1); Participant did not have a Voice_4 file at their Final Visit they had no phone calls in their phone call log   


## 224

- Duplicate number (9203363023) in contacts excel file removed. This is the participant’s parent’s home phone. She has different responses for each parent, but claims that she speaks to each of them the same amount from the home phone. The number is now only associated with the top parent. 


## 225

- Duplicate entry for home number removed (95289427568). Associated with top parent now.   


## 240

- There are duplicate entries for the participants' spouse/significant other in the Contacts file because their spouse/significant other moved residences and we wanted to make sure that there wasn't confusion over why we had another location for a contact/ensure that someone unfamiliar with the participant and data collection could see that it's the same person with a new address Ð that the contact is linked to the correct location.


## 242

- At follow up 3 participant reported that her fiance had been using her phone while he was without a phone so quite a few contacts were marked as irrelevant/spam if her fiance had been the one on the call.   

## 243

- Participant missed their final visit so we only have 2 Call and SMS logs from them  


## 248

- FU3 - Unable to get call log data from their backup. Note captured in their participant data log.; Unable to extract the Voice file from the iPhone backup at Follow up 3. We were only able to get the SMS file; duplicate numbers in the interview data left because answers changed for the contact

## 259

- I was unable to locate the voice file after doing the phone backup during FU2. I went over contacts from the SMS file only. Susan and Jill were working on figuring out whether the voice file was saved under a new name but had not figured this out prior to the session completing. If it is resolved prior to Follow-Up #3 I will collect them then; Susan completed phone transfer during FU3; Several contacts were real people but the participant did not have the numbers saved. I elected to skip these numbers rather than mark irrelevant on the off chance that at the next visit the participant remembers who these people are. A lot of times the numbers were a part of a large group text message and the person was not someone that the participant ever spoke to directly

## 268

- There was an issue collecting the voice file during phone transfer at FU2 and a voice file was not collected. We went over SMS as normal; Susan collected SMS and Voice files through Imazing during FU3.


## 269

- Several numbers came up as calls or texts but when searching the phone to find these numbers no texts or missed calls would come up. These were marked as irrelevant/spam (FU2)   