---
title: "EMA Lapse Notes"
author: "Kendra Wyant"
output: html_document
---

## 001

-  Participant stopped receiving text messages from the survey line on 4/19/17. RA attempted to troubleshoot with participant over the telephone, but RA attempts were unsuccessful. Lab Manager spent time troubleshooting issue with participant while he was in the lab and discovered that he had the survey line blocked. The number was unblocked and test text messages were sent and received. The issue is now solved.   

**First lab visit after 4/19/17 from visit dates is 5/1/17. EMA's may be missing or incomplete from 4/19/17 - 5/1/17**   


## 002

- Participant reports that she has received multiple “bedtime” surveys. She reports that three EMAs have come in at 1:30 am. She also reports that she has gotten double “bedtime” EMAs delivered.    


## 003  

- Participant reported that she has received her bedtime [EMA] survey late a handful of times.   


## 017

- No-Show for FU#1 and FU #2 (Spouse called to report that participant entered an in-patient treatment program); Very low compliance.    


## 028

- At FU2 - participant acknowledged that they hadn’t been as diligent in answering surveys, but will make a concerted effort in their final month of study participation.     

## 029

- last EMA 1/22/17  


## 031

- 12/4/2017: Participant 031 was getting EMA surveys with test as the embedded subid instead of 031. The problem in Survey Signal was corrected and the EMAs that 031 had completed were edited in Qualtrics so that the subid is now 031 (see next bullet for more info).   

- 2/26/2018: in EMAM morning battery subid test at the following UTCs were changed to subid 031 - 1512392452; 1512309553; 1512227465; 1512133243; 1512047106; 1511960486; 2/26/2018: in EMAL later battery subid test at the following utcs were changed to subid 31 - 1512407036; 1512335063; 1512326855; 1512269438; 1512178633; 1512169637; 1512087509; 1512074607; 1512006978; 1511984753.   

- 2/27/2018: Reviewed unfinished EMA responses with the participant at follow-up 3. They had no lapses and did not report any lapses.   


## 032

- Participant lost their phone for a few days in December


## 033

- 03/15/2018 - Participant completed her final study visit. RA reviewed the incomplete/”false” surveys with the participant. The participant completed the first question on EMA Later surveys dated 1/1/18 and 1/16/18. The participant reported that she accidentally answered the first question as “yes” for the 1/1/18 survey as it should have been no. On the 1/16/18 survey the participant answered “no,” and this is accurate. This information is also in the RISK project Data Log. 


## 034

- 3/27/2018: Participant 034 – RA reviewed participant’s unfinished response recorded on February 13th, 2018. Participant confirmed that they answered EMAM_1.1-1.5 correctly, but simply didn’t finish the rest of the survey.     


## 042

- One ema was completed during this reported lapse at 12:56 AM (4/10/18). Given how early this is it still seems possible that they had been drinking at the reported times; No emas were completed on 03/15.   


## 043

- One ema was completed on 04/08 at 16:20 with no lapses to report; No emas were completed in between that one and this survey lending support that this was a legitimately reported lapse   

**Not sure I understand this note. Did not come from data log**


## 044

- About 4 surveys were not delivered to the participants phone. There was not a pattern with these EMAs, but the participant was advised to inform the study staff if the issue worsened.  


## 047

- Was not receiving EMA messages between 04/06/2018 and 04/17/2018.; Participant has been having EMA issues since 4/5/2018; Participant was not consistent with responding to EMAs when they were being received, which is why they were discontinued; EMA issues still unresolved as of 4/16/2018; Had a lapse on 4/10/2018 at 4:00pm recorded by RA Jill on 4/11/2018 after tech troubleshooting appointment     


**Found table of lapses in data log**    
Lapse Start Date	Lapse End Date	Lapse Start Time	Lapse End Time	Survey Reported	Confirmed/Fixed     
4/25/2018	4/25/2018	7pm	10pm	EMAM	Confirmed    
4/17/2018	4/17/2018	6pm	7pm	EMAL	Confirmed    
4/16/2018	4/16/2018	8pm	10pm	EMAL	Confirmed    
4/5/2018	4/5/2018	9pm	9pm	EMAL	Confirmed    
4/5/2018	4/5/2018	9pm	11pm	EMAL	Confirmed    
4/3/2018	4/3/2018	8pm	10pm	EMAL	Confirmed    
4/2/2018	4/2/2018	3pm	4pm	EMAL	Confirmed   
3/31/2018	3/31/2018	8pm	11pm	EMAL	Confirmed   
3/28/2018	3/28/2018	8pm	11pm	EMAL	Confirmed   
3/28/2018	3/28/2018	7pm	7pm	EMAL	Confirmed    
3/25/2018	3/25/2018	8pm	11pm	EMAL	Confirmed    
3/24/2018	3/25/2018	11pm	Midnight	EMAL	Confirmed    

  
## 048

- Audio on 04/01 mentioned drinking and sub did their ema at 9pm so even though there was no explicit note that the drinking was specifically for that day I think it is a safe assumption. However they already reported a lapse on 04/01 from 17:00-21:00. Their audio message on 04/02 mentioned that they were going to the brewer game and were going to drink there. This leads me to believe that this is a typo for 04/02 instead of 04/01



## 050 

**Table of confirmed lapses in subids data log**     
Lapse Start Date	Lapse End Date	Lapse Start Time	Lapse End Time	Survey Reported	Confirmed/Fixed    
3/27/2018	3/27/2018	10pm	Midnight	EMAM	Confirmed    
3/26/2018	3/26/2018	3pm	7pm	EMAL	Confirmed    
3/26/2018	3/26/2018	3pm	9pm	EMAL	Confirmed    
3/23/2018	3/24/2018	10pm	10am	EMAM	Confirmed    


## 052

- 5/3/2018: Participant reported an issue with their survey link Ð while investigating the issue we found that the participant was getting Morning EMA (EMAM) links for both their Morning Survey and their Evening Survey. The Evening survey link has been updated as of 5/3/18.   


## 053   

**Table of confirmed or false lapses in subid's data log**    
Lapse Start Date	Lapse End Date	Lapse Start Time	Lapse End Time	Survey Reported	Confirmed/Fixed    
5/15/2018	5/15/2018	1pm	1pm	EMAL	Confirmed    
5/11/2018	5/11/2018	8am	9am	EMAM	Confirmed    
5/7/2018	5/7/2018	3pm	8pm	EMAM	Confirmed    
4/24/2018	4/24/2018	Noon	Noon	EMAL	Confirmed   
4/7/2018	4/7/2018	7pm	10pm	EMAL	Confirmed   
4/4/2018	4/3/2018	8pm	11pm	EMAL	Fixed    
4/3/2018	4/3/2018	2pm	9pm	EMAM	Confirmed     
3/28/2018	3/28/2018	6pm	6pm	EMAL	Confirmed     

False entries marked ‘yes’: UTC time stamps = 1529903331, 1525734722    
1526416845 – 5/14/2018 – 5/15/2018 1am to 4pm    
1522811854 – fix to 4/4 – 4/4 8-11pm    
1526411694 – repeat reported lapse. Marked 5/15-5/15 1-1pm, but that lapse was already reported.     



## 054  

**Table of confirmed or false lapses in subid's data log**    
Lapse Start Date	Lapse End Date	Lapse Start Time	Lapse End Time	Survey Reported	Confirmed/Fixed    
3/30/2018	3/30/2018	7:00 PM	10:00 PM	EMAL	Confirmed    
4/10/2018	4/10/2018	7:00 PM	7:00 PM	EMAL	Confirmed  
4/12/2018	4/12/2018	4:00 PM	4:00 PM	EMAL	Confirmed  
4/14/2018	4/14/2018	5:00 PM	5:00 PM	EMAL	Confirmed  
4/20/2018	4/20/2018	6:00 PM	9:00 PM	EMAL	Confirmed  
4/27/2018	4/27/2018	6:00 PM	7:00 PM	EMAL	Confirmed  
5/1/2018	5/1/2018	6:00 PM	8:00 PM	EMAL	Confirmed  
5/9/2018	5/9/2018	7:00 PM	7:00 PM	EMAL	Confirmed  
5/12/2018	5/12/2018	8:00 PM	9:00 PM	EMAM	Confirmed  
5/12/2018	5/12/2018	7:00 PM	9:00 PM	EMAM	Confirmed  
5/15/2018	5/15/2018	5:00 PM	5:00 PM	EMAL	Confirmed  
5/18/2018	5/18/2018	7:00 PM	8:00 PM	EMAL	Confirmed  
5/19/2018	5/19/2018	7:00 PM	7:00 PM	EMAL	Confirmed  
5/22/2018	5/22/2018	7:00 PM	8:00 PM	EMAL	Confirmed  
5/23/2018	5/23/2018	8:00 PM	9:00 PM	EMAL	Confirmed  
5/24/2018	5/24/2018	7:00 PM	7:00 PM	EMAL	Confirmed  
5/25/2018	5/25/2018	7:00 PM	8:00 PM	EMAL	Confirmed  
5/27/2018	5/27/2018	11:00 AM	1:00 PM	EMAL	Confirmed  
5/30/2018	5/30/2018	8:00 PM	8:00 PM	EMAL	Confirmed  
5/31/2018	5/31/2018	6:00 PM	8:00 PM	EMAL	Confirmed  
5/31/2018	5/31/2018	9:00 PM	10:00 PM	EMAM	Confirmed  
6/2/2018	6/2/2018	9:00 PM	9:00 PM	EMAM	Confirmed  
6/9/2018	6/9/2018	6:00 PM	6:00 PM	EMAL	Confirmed  
6/9/2018	6/9/2018	6:00 PM	8:00 PM	EMAL	Confirmed  
6/10/2018	6/10/2018	6:00 PM	8:00 PM	EMAL	Confirmed  
6/11/2018	6/11/2018	5:00 PM	5:00 PM	EMAL	Confirmed  
6/12/2018	6/12/2018	7:00 PM	8:00 PM	EMAL	Confirmed  
6/12/2018	6/12/2018	9:00 PM	11:00 PM	EMAM	Confirmed  
6/14/2018	6/14/2018	5:00 PM	6:00 PM	EMAL	Confirmed  
6/15/2018	6/15/2018	6:00 PM	8:00 PM	EMAL	Confirmed  
6/15/2018	6/15/2018	8:00 PM	11:00 PM	EMAM	Confirmed  
6/22/2018	6/22/2018	7:00 PM	10:00 PM	EMAM	Confirmed  


False surveys – UTC = 1525530507, Marked ‘yes’ accidentally.    



## 056

- 4/10/2018 - 4/13/2018: Participant received an extra 10 randomized signals a day due to an error made while setting up their Survey Signal EMAs. They responded to two of those signals per usual, but responded to one in the evening in place of their evening signal. The issue was resolved and the participant is receiving the appropriate amount of EMAs. The time stamps for the completed surveys are: 1523388770; 1523404266;	1523418062;	1523486375; 1523502110; 1523553357; 1523569657;	1523588485;	1523638103; 1523666318; 1523674955.   
- Participant was having difficulties responding to EMAs at job (WiFi may have been blocking the site) but they have a new job for the summer so response rates should increase.    
- Participant reported several lapses around 4/20/18.    

					

## 062

- Due to an error in Survey Signal participant did not begin receiving surveys until 5/19/2018 when they were supposed to start receiving surveys 5/18/2018. Participant stopped responding to surveys after 5/29/2018. We tried to reach out to them several times unsuccessfully.   


## 064

- Participant experienced a handful of times over the course of their participation during which their phone service was disconnected (as they had a state subsidized phone) so they were occasionally unable to complete the surveys if they were not connected to wifi.  
- The participant responded “yes” to EMA_1 on one survey with UTC time stamp of: 1532539935. The participant reported that they had not intended to answer yes.    


## 076   

- Due to an error in Survey Signal participant did not receive their EMAM survey for 6/28. The participant was getting the EMAL survey link as their morning survey so they have 4 EMAL's for 6/28/2018. The issue has been corrected and participant should begin getting their surveys starting 6/29.   


## 079  

- Data log says this sub had a brain injury and suffers from memory issues; This could explain why it took so long to report this lapse; However he did report a lapse on 09/02 20:00 at 10am on 09/03 which makes me a little skeptical and think it is possible that that this is supposed to be 09/03; Without any audio messages around this time I think it is impossible to say.   
- Participant was not receiving EMAM for 6/23 6/24 and 6/25 due to an issue with the survey link. It was corrected on 6/25 so participant will be getting EMAM surveys.   


## 080

- The participant also changed their number before their final visit and did not notify the lab, so they did not complete any surveys since early September.   


## 082

- Participant stopped responding to surveys 7/31/18 (phone was stolen)    


## 084 

- Participant was out of the country 8/8-8/16 and were unable to complete surveys    
- Problems with phone throughout study     
- Participant called 7/19/2018 at approximately 1:45pm to report that they had misplaced their phone. They had left their phone on a bus. They are working with Metro transit services to get their phone returned to them but will be missing some data due to the loss of their phone for a day    
- Participant came in on 7/31/2018 to get apps and register surveys on a different phone as they were having problems with their state subsidized phone    

## 086

- At 6pm on 10/13 sub reported a lapse on 10/13 from 12-3pm; This ema is the next one that was completed so may have ended up drinking a lot longer than they intended    

## 098

- The participant reported that she seems to be getting the random EMA surveys too close together.   


## 100

- Audio message on 09/11 reported that they were happy to get out of the hospital on Sunday (09/09). Not sure how long they were in the hospital for; They did not complete any surveys on 09/05 but they did complete all 4 on 09/06   

## 104

- Completed through follow-up #2; Participant decided to discontinue at Follow up 2 as they were struggling to gain sobriety    
- Participant reported lapses every day while on study  


## 116

- Longer lapses for this participant seem fairly common; no info in data logs or audio messages   


## 118

- On 10/04 sub states that they have not drank nothing that I have and then it is inaudible; No info in data logs.   

## 119

- On 10/31 subs audio mentioned that they had missed several days because they relapsed and were trying to get back on track; This is the only lapse that was reported while on study; However it is unclear if this lapse report is correct. They had answered 4 surveys on 10/28 saying they did not lapse.  


## 128

- Audio message for 10/05 reports that the sub has been drinking off and on for the last 2 or 3 days; Lots of lapses reported on 10/03-10/05; Some overlap but not all which further emphasizes info from audio message; Audio message on 10/17 reported drinking the night before - Lots of lapses being reported during time; Participant mentioned that she drank some on 11/18 but not a ton; She also reported on 11/17 that she has not been fighting any urges; No explicit mention of drinking in audio message just that sub was not looking forward to going home; Lots of little lapses reported around this time (12/3/18)    

## 135

- Participant reported they were receiving 6 surveys per day. Upon further investigation the participant had accidentally been registered to receive the Randomized surveys for another participant (#101) who was deemed ineligible before their Intake visit. The participant was receiving their own Randomized surveys but was responding to theirs as well as the surveys they were accidentally registered for.   
- Surveys they responded to as subid 101 are: 1540308811; 1540243093; 1540219943; 1540083292; 1540058950; 1539988243; 1539976186; 1539970713; 1539908562; 1539884290; 1539829752; 1539793359; 1539740060; 1539113249; 1539707263; 1539558908; 1539545266; 1539475283; 1539381949; 1539374460; 1539298977; 1539295456; 1539206885; 1539183666; 1539113270; 1539027346; 1539027286; 1538947401; 1538932892; 1538867564; 1538852234; 1538783590; 153875201 (this utc is one digit short?)   


## 139

- Participant experienced technical difficulties and was unable to complete EMA or audio surveys from 12/25/18 - 01/03/2019.  

## 149

- Reported lapse 1/10/2019 and stopped completing EMAM after that date. Participant stopped completing EMAL after 1/11/2019. They are not off study until 1/24/2019.   


## 156

- Low EMA compliance; no reported lapses  

## 166

- 2/11/19: Participant EMAM links weren’t working over the weekend and today (the 11th). Checked the links and replaced them with functioning links. Participant just missed the first few days; 5/14/2019: Participant expressed that they struggled with abstinence throughout the study.  

## 169

- Participant was at their fathers house from 3/27 - 3/29 and do not get reception in that area. May not be able to respond to many surveys.   

**Table of confirmed lapses in their data log**     
Lapse Start Date	Lapse End Date	Lapse Start Time	Lapse End Time	Survey Reported	Confirmed/Fixed   
5/2/2019	5/3/2019	9pm	11pm	EMAM	Fixed   
5/2/2019	5/2/2019	7pm	8pm	EMAL	Confirmed   
4/26/2019	4/26/2019	8pm	8pm	EMAL	Confirmed   
4/26/2019	4/27/2019	8pm	5pm	EMAL	Fixed   
4/25/2019	4/26/2019	11pm	Midnight	EMAM	Fixed   
4/22/2019	4/22/2019	11pm	Midnight	EMAM	Confirmed   
4/22/2019	4/22/2019	4pm	4pm	EMAL	Confirmed   
4/4/2019	4/4/2019	9pm	11pm	EMAM	Confirmed   
4/4/2019	4/4/2019	1am	2am	EMAL	Confirmed    
4/3/2019	4/3/2019	8pm	8pm	EMAL	Confirmed    
3/30/2019	3/31/2019	10pm	Midnight	EMAM	Confirmed    
3/2/2019	3/2/2019	8pm	8pm	EMAM	Confirmed    
2/22/2019	2/22/2019	7pm	8pm	EMAL	Confirmed   
2/22/2019	2/22/2019	4pm	5pm	EMAL	Confirmed   
2/16/2019	2/16/2019	11am	11am	EMAL	Confirmed   

UTC time stamp = 1556913222 should be 5/2 – 5/2 from 9pm – 11pm   
UTC time stamp = 1556290957 should be 4/25 – 4/25 11pm – Midnight   
UTC time stamp = 1556322909 should be 4/26 – 4/26 from 5pm – 8pm   



## 172

- Called participant 3/15/19 after not getting EMA responses for a week. Participant explained that they were having issues with their cell phone. They plan on getting the problem looked at and possibly getting a different phone. They will call and set up an appointment if they do get a new phone; Participant never contacted us about their phone. When called for their follow up appointment their phone was disconnected. We considered them discontinued.   
- No EMAM since 2/28/19 and no EMAL since 3/8/19   


## 173

- Participant hadn’t responded to surveys since 2/5/19 - picked back up on 2/14/19 (participant called on 2/14/19 and stated they were interested in continuing study participation they were just having a hard time but are ready to get back on track); 3/8/19: Participant’s EMA compliance was never over 15% went weeks without answering and no-called no-showed to their Follow Up 1 therefore they are considered discontinued from study participation. 


## 175

- In audio message from 02/07/2019 participant reported not having received an evening survey on 02/06/2019.  

**Table of confirmed lapses in data log**   
Lapse Start Date	Lapse End Date	Lapse Start Time	Lapse End Time	Survey Reported	Confirmed/Fixed    
4/25/2019	4/25/2019	Noon	Noon	EMAL	Confirmed   
4/6/2019	4/6/2019	5pm	5pm	EMAL	Confirmed    



## 179

- No lapses reported.   


## 185

- At the Intake visit, 02/20/2019 the participants phone was not receiving every message we sent. The phone did not receive the Randomized Survey registration link (tried sending twice deleted the survey then tried again and still did not receive). The practice audio message and practice morning survey were not delivered but the practice evening survey was completed; As of 02/21/2019 the participant was still not registered for the Randomized surveys; As of 02/22/2019 the participant was registered and began responding to Randomized surveys.  

## 183

- No lapses reported.


## 187

- No lapses reported.  

## 188

- Participant mistakenly answered EMA with UTC 1557713610 as Yes when they meant to say no. They did not report a lapse while on study.    


## 189

- Participant responded ‘uncertain’ for the lapse with UTC 1558294514. At their final visit we talked about their lapses and their uncertain response. The participant stated that they were devastated that they relapsed and at that point were uncertain whether they could/wanted to maintain abstinence but they also acknowledged that they were drunk at the time of responding to the survey so they aren’t completely sure what they were thinking at that moment. They were able to regain sobriety and have recommitted themselves to remaining abstinent.  

## 190

- EMAM UTC 1558108786 unfinished survey – lapse was reported but participant could not remember the exact date or time.   

## 191

- Participant appears to have stopped responding to EMA surveys on 5/10/2019. Staff called participant on 5/23/2019 to determine if the surveys are still coming in- waiting to hear back; Staff heard back from participant on 5/23/2019 and the participant reported having left a voicemail with the staff earlier in the month reporting that they were not receiving any surveys.   

**Table of confirmed and fixed lapses in subid's data log**   
Lapse Start Date	Lapse End Date	Lapse Start Time	Lapse End Time	Survey Reported	Confirmed/Fixed    
05/28/2019	05/28/2019	3pm	4pm	EMAL	Confirmed    
05/27/2019	05/26/2019	10pm	7pm	EMAL	Fixed    
05/25/2019	05/25/2019	1pm	7pm	EMAM	Confirmed    
4/25/2019	4/25/2019	7pm	6pm	EMAL	Fixed   
4/14/2019	4/14/2019	6pm	7am	EMAL	Confirmed   
4/14/2019	4/14/2019	Noon	Noon	EMAL	Confirmed   
4/16/2019	4/9/2019	9pm	2pm	EMAL	Fixed    
0400	4/7/2019	5pm	5pm	EMAL	Fixed   
4/3/2019	4/3/2019	Noon	10am	EMAL	Fixed   
300	4/1/2019	3pm	3pm	EMAL	Fixed   
3/22/2019	7pm	7pm	11pm	EMAL	Fixed   
3/22/2019	3/22/2019	7pm	10pm	EMAM	Confirmed   
3/19/2019	3/19/2019	7pm	7pm	EMAL	Confirmed   
3/15/2019	3/16/2019	3pm	2pm	EMAL	Fixed   
3/15/2019	3/15/2019	7pm	6pm	EMAL	Fixed   
3/13/2019	3/14/2019	2pm	2pm	EMAL	Confirmed   


5/26 – 5/27 from 3pm – 4pm should be 5/26 – 5/26 from 3pm – 4pm   
Lapse on 4/25 should be from 7pm to 8pm   
Lapse on 4/14 should be from 7am to 6pm   
4/16 – 4/9 frm 9pm – 2pm should be 4/9 – 4/9 from 2pm to 9pm   
Lapse on 4/7 should be 4/7 – 4/7 at 5pm   
Lapse on 4/3 should be from 10am to 12pm   
Lapse on 4/1 should be 4/1 – 4/1 at 3pm   
Lapse on 3/22 should be 3/22 – 3/22 from 7pm – 11pm   
Lapse on 3/15 – 3/16 from 3pm to 2pm should be 3/16 – 3/16 from 2pm to 3pm   
Lapse on 3/15 should be from 6pm to 7pm   

## 193

- Participant had moderate compliance and was reporting receiving all of the surveys during the day but was failing to complete the morning survey. Staff offered to change the time of the survey but participant said they would continue to work on it. Upon further investigation it seems as though the participant was not receiving the morning surveys. On Survey Signal it appears as though they were not registered for the Morning survey even though they received the test survey and a morning survey the day after their Intake. This participant only completed one morning EMA while on-study.    

## 201

- No lapses reported.   


## 204  

- Serious problems with poor EMA compliance   
- Participant did not do many surveys during their second month of participation. At their Follow-up 2 visit, they reported several lapses that were not documented in their EMAs. The estimated dates and times are   
  - 05/01/2019 9:00pm – 11:00pm  
  -	05/02/2019 5:00pm – 9:00pm and 9:00pm – 12:00am  
  -	05/03/2019 12:00am – 2:00am and 9:00pm – 11:00pm  
  -	05/04/2019 9:00am – 4:00pm  
  -	05/10/2019 5:00pm – 12:00am  
  -	05/11/2019 12:00am – 2:00am  
- Participant did a total of 5 surveys in between follow-up2 and follow-up3. Participant reported that she did not like doing the surveys after a while so she stopped completing them. I collected lapses from her even though she did not complete her surveys and she reported that the lapse she reported with timestamp: 1558123879 was not 1 long drinking episode, but 3 individual ones lasting from 9pm each night and going until Midnight. She also reported that she probably drank beginning 05/16 through 06/04 from 9pm until Midnight.    


## 205

- Participant’s compliance also started to drop and ceased to complete surveys regularly on 6/7/19.   
- No lapses reported.   


## 207

- Unable to respond to surveys for 2 weeks due to being out of the country and not having reception    

## 208

- No lapses reported.   

## 211

- Participant lapsed a lot during participation; early morning/long lapses; no audios around this time.   

## 212


- Participant fell asleep while taking their surveys but insisted that they didn't need to reschedule their appointment. Participant admitted to being hungover from drinking all night the night before but was not noticeably intoxicated. Participant was asked if they had reported the lapse and they said "no I havenÕt done any surveys today" (their visit was at 1:00 pm).    
- Audio on 4/17 reported that drinking has been an issue. No specific info about the lapse. They denied having a lapse to report 3 times during the alleged lapse; Participant divulged at their follow up visit that they drank the night before their visit (5/15/19 - 5/16/19) but they never formally reported the lapse.    


## 213

- Participant had people in his house using his phone and it is hard for him to do surveys. He will try to answer them more. Keiser adjusted the time of the evening survey to come in at 9pm instead of 10pm.; Participant reported having drank alcohol nearly every day during the lapse dates provided - They reported the first day (05/13/2019) being the heaviest day and the subsequent dates being a little lighter. They did not recall times for lapses when asked during their Follow-up 2 visit; The participant did not complete any ema between 5/7-5/21; They did not complete any audio messages between 5/04-5/22; Their 5/22 and 5/27 audio messages both reference that they’ve “been drinking” and on 5/30 they say they are “trying to get back on track”; Participant reported having drank at the following times on listed dates: 5/25: 11pm-12am 5/26: 6pm -8pm 5/27: 6pm-8pm. Participant reported these were estimates of the times spent drinking on this weekend.     


**lapse table from data log**   
Start Date	End Date	Start Time	End Time	Timestamp	Needs to be fixed by John/noted in datalog:   
05/13/2019	05/21/2019	9pm	5pm	1558482409	Participant reported having drank alcohol nearly every day during the lapse dates provided. They reported the first day, 05/13/2019 being the heaviest day, and the subsequent dates being a little lighter. They did not recall times for lapses when asked during their Follow-up 2 visit.     

05/25/2019	05/27/2019	11pm	6pm	1559003693	Participant estimated having drank at the following times on listed dates:    
5/25: 11pm – 12am    
5/26: 6pm – 8pm    
5/27: 6pm – 8pm    


## 214

**lapse corrections from data log**   
Start Date	End Date	Start Time	End Time	Timestamp	Needs to be fixed by John/noted in datalog:    
6/23/2019	6/23/2019	5pm	11pm	1561352949	Noted: should be removed    
6/23/2019	6/23/2019	5pm	9pm	1561401216	This is the correct timeframe     
   

## 218

**lapse correction from data log**    
Start Date	 End Date	Start Time	End Time	Timestamp	Needs to be fixed by John/noted in datalog:     
5/14/2019	5/15/2019	8pm	2pm	1557956376	Noted: should be 8pm – 2am    

  
## 221

- Sub reported quite a few longer lapses during participation; No audios or notes in data log regarding this time; No emas were completed during the alleged lapse window lending support for this.   

## 223

- No surveys received 5-3 through 5-6   

## 225

- This is the only lapse she reported during her participation but her audio messages definitely do not reflect her drinking during this entire period; On 6/19 participant reported that they felt like crap because they relapsed; On 6/20 participant reported that they were 2 days sober; They did not complete an audio message between 6/14-6/19 however messages between 6/5-6/14 do not give any indication that she was drinking   


## 242 

- Participant reported being in jail September 13 2019 through September 16 2019.   


## 252

- Last survey of the night didn’t work (9/19/19)


## 263

- No emas were completed on 09/17 which supports why it took so long to report it and the possibility that they lapsed this long   

## 264

- Participant reported that they were not getting their surveys as of 10/18/2019 - we investigated and this issue is affecting AT&T participants; Participant was unable to get surveys between October 25th and most of November 1st - they started getting surveys the evening of November 1st   


## 265

- Participant continued doing surveys despite not contacting staff about remained interest in the study. Last EMA was completed on 10/30/19 which is the same day that the participant was discontinued and surveys were stopped


## 268

- This person had 3 separate lapses on 10/26. She reported a lapse from 1pm-3pm and 8pm-9pm (same as this one but reported at 10am) This means that she probably lapsed at some point between 4pm and 8pm but reported the time wrong
- Participant called us on 10/18/2019 to let us know that she had not received any surveys today. After talking with survey signal it was believed that an issue with ATT was causing the text messages to be blocked from getting delivered. The participant tried to troubleshoot with ATT over the phone but ATT said everything looked fine on their end. Because it is a Friday Susan and Megan decided to set up new EMAs (Risk - 268_2) that would be sent to the participant's email address.   

## 270

- The participant attended her final visit but declined to give unreported contacts and locations. She didn’t directly decline but she passively declined by being uncooperative and saying “I have no idea” several times when RA attempted to review new locations and numbers with the participant.   
- The participant reported a lapse on 11/02/2019 (UTC: 1572734206).  EMAL_1.3 should also be 11/02/2019. The time listed in EMAL_1.4 is incorrect. The participant reported that she drank a lot so she doesn’t recall much from this drinking episode.   
- The participant reported a lapse on 11/02/2019. The participant reported that she drank a lot so she doesn’t recall much from this drinking episode; In her audio message on 11/3 the participant reports having 2 shots. she reports it wasnt her intention to get drunk but to resolve pain and she stopped when she wasnt in pain anymore; No other emas reference a time period about the use.    
