---
title: "Demos how to manually make an rset object for gps splits per GA tech splits"
author: "John Curtin"
date: "`r lubridate::today()`"
output: 
  html_document:
    toc: true 
    toc_depth: 4
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = dplyr::if_else(Sys.info()[["sysname"]] == "Windows",
      "P:/studydata/risk/knits/gps", 
      "/Volumes/private/studydata/risk/knits/gps")
    )
  })
---

### Set up Environment

Chunk Defaults
```{r defaults, include=FALSE}
knitr::opts_chunk$set(attr.output='style="max-height: 500px;"')
```

Absolute paths
```{r, paths}

switch (Sys.info()[['sysname']],
        # PC paths
        Windows = {
          path_gps <- "P:/studydata/risk/data_processed/gps"
          path_shared <- "P:/studydata/risk/data_processed/shared"
          path_lab_support <- "P:/toolboxes/lab_support"},

        # IOS paths
        Darwin = {
          path_gps <- "/Volumes/private/studydata/risk/data_processed/gps"
          path_shared <- "/Volumes/private/studydata/risk/data_processed/shared"
          path_lab_support <- "/Volumes/toolboxes/lab_support"}
        )
```


Packages for lab workflow 
```{r, packages_workflow, message=FALSE, warning=FALSE}

library(conflicted) # detect and warn about function conflicts
conflict_prefer("filter", "dplyr")
# conflict_prefer("select", "dplyr")

library(here)  # establish project directory consistently as working directory
```

Packages for script
```{r, packages_script, message=FALSE, warning=FALSE}

# for data wrangling
library(tidyverse)  # always need this
library(rsample)
library(janitor)

source(here("gps", "fun_gps.R"))  # for make_rset()
```


### Demo code starts here

Get labels and subids for splits. 

For real rset d should include both Y and all X.
```{r}
d <- read_csv(here(path_gps, "labels_05.csv")) %>% 
  glimpse()

# folds in columns
train_ids <- read_csv(here(path_gps, "train_ids.csv"), col_names = FALSE) %>% 
  glimpse()
```

Make rset
```{r}
rset <- make_rset(train_ids, d)
```

EDA on rset
```{r}
rset

rset$splits[[1]]
analysis(rset$splits[[1]]) %>% 
  glimpse() %>% 
  tabyl(subid)
assessment(rset$splits[[1]]) %>% 
  glimpse() %>% 
  tabyl(subid)

rset$splits[[2]]
analysis(rset$splits[[2]]) %>% 
  glimpse() %>% 
  tabyl(subid)
assessment(rset$splits[[2]]) %>% 
  glimpse() %>% 
  tabyl(subid)

rset$splits[[3]]
analysis(rset$splits[[3]]) %>% 
  glimpse() %>% 
  tabyl(subid)
assessment(rset$splits[[3]]) %>% 
  glimpse() %>% 
  tabyl(subid)
```